//! The engine's cbuffer name → index table, read verbatim from `tool.exe`
//! (`off_141939ED8`, 113 `char*` populated 1-based by `sub_140CBD1E0`). This
//! index is packed into the high byte of a constant's `register start`
//! (`(index << 8) | (offset >> shift)`), so a byte-matching constant table must
//! use these exact numbers. It is one flat namespace shared by VS and PS.
//!
//! Contract reference: h3lm `docs/SHADER_COMPILE.md` §8b and the cbuffer-index
//! reversal (`re_cbuffer_index.md`).

/// The 113 cbuffer names in table order; the engine index is `position + 1`.
pub const CBUFFER_NAMES: [&str; 113] = [
    "CopyToScreenPS",
    "YUVToRGBPS",
    "ApplyColorMatrixPS",
    "AU2PlaylistRatingPS",
    "BSplineResamplePS",
    "CHUDVS",
    "CHUDPS",
    "CHUDWidgetPS",
    "CHUDScreenFlashPS",
    "CHUDCortanaPS",
    "ContrailRenderVS",
    "ContrailSpawnVS",
    "ContrailUpdateVS",
    "CopyTargetPS",
    "CropPS",
    "CubeMapPS",
    "CustomGammaCorrectPS",
    "Debug2DPS",
    "DecalVS",
    "DecalPS",
    "DecoratorsLightsVS",
    "DecoratorsVS",
    "DecoratorsGlobalsVS",
    "DecoratorsEditVS",
    "DecoratorsPS",
    "DisplacementPS",
    "DisplacementMotionBlurPS",
    "DownsamplePS",
    "FinalCompositePS",
    "FinalCompositeDOFPS",
    "FXAAVS",
    "FXAAPS",
    "GammaCorrectPS",
    "VertexCompressionVS",
    "AlphaTestShaderVS",
    "DominantLightPS",
    "DynamicLightPS",
    "ActiveCamoPS",
    "ViewVS",
    "ExposureVS",
    "AtmosphereVS",
    "LightingVS",
    "ShadowProjVS",
    "ViewPS",
    "ExposurePS",
    "LightingPS",
    "MiscPS",
    "LightmapCompressPS",
    "SimpleLightsPS",
    "ImplicitHillVS",
    "Kernel5PS",
    "LegacyMeterPS",
    "LensFlareVS",
    "LensFlarePS",
    "LightshaftsPS",
    "OverheadMapGeometryVS",
    "OverheadMapGeometryPS",
    "ParticleIndex",
    "ParticleRenderVS",
    "ParticleRenderPS",
    "ParticleSpawnVS",
    "ParticleUpdateVS",
    "PatchyFogPS",
    "PatchyFogSheetPS",
    "PlayerEmblemPS",
    "PostProcessPS",
    "RadialBlurPS",
    "Rotate2DPS",
    "ScreenshotDisplayPS",
    "ScreenshotMemExportPS",
    "ShadowApplyPS",
    "ShadowGeometryPS",
    "ShieldImpactVS",
    "ShieldImpactPS",
    "ShieldMeterPS",
    "SniperScopePS",
    "SpikeBlurPS",
    "SSAOVS",
    "SSAOPS",
    "StencilStipplePS",
    "WaterVS",
    "WaterPS",
    "WaterTessellationVS",
    "WaterRippleApplyVS",
    "WaterSharedVS",
    "WaterSharedPS",
    "WindVS",
    "YUVToRGBShaderPS",
    "ParticleEmitter",
    "ParticleState",
    "Beam",
    "BeamState",
    "BeamStrip",
    "Contrail",
    "ContrailState",
    "LightVolume",
    "LightVolumeState",
    "LightVolumeStrip",
    "ParticleRenderMeshVS",
    "BeamIndex",
    "ContrailIndex",
    "ContrailStrip",
    "LightVolumeIndex",
    "WaterRippleIndex",
    "WaterRippleUpdateVS",
    "DynamicLightClipVS",
    "FSRCS",
    "GlobalPS",
    "ParametersVSExterns",
    "ParametersPSExterns",
    "SkinningVS",
    "ParametersVS",
    "ParametersPS",
];

/// The engine index (1-based) for a cbuffer name, or `None` if it is not in the
/// table (the engine reports "constant buffer %s not found" and fails).
pub fn cbuffer_index(name: &str) -> Option<u32> {
    CBUFFER_NAMES.iter().position(|n| *n == name).map(|p| (p + 1) as u32)
}
