// @generated by blam-tags-bindgen. DO NOT EDIT.
// Regenerate with `cargo run -p blam-tags-bindgen`.
#![allow(clippy::all)]
use pyo3::prelude::*;
use pyo3::types::PyAny;
#[allow(unused_imports)]
use crate::manual::*;

/// Convert a Python-supplied list into a fixed-size Rust array,
/// reporting the arity mismatch as a Python `ValueError` rather than
/// panicking.
fn __seq_to_array<T, const N: usize>(v: Vec<T>) -> PyResult<[T; N]> {
    let got = v.len();
    <[T; N]>::try_from(v).map_err(|_| {
        pyo3::exceptions::PyValueError::new_err(format!(
            "expected a sequence of {N} elements, got {got}"
        ))
    })
}

/// Parsed form of a `ti][` api-interop chunk payload.
/// 
/// The 12-byte shape matches BCS's `s_tag_interop { descriptor,
/// address, definition_address }`. `address` is the runtime pointer
/// slot — BCS's writer zeroes it to `UINT_MAX` on save, so the
/// canonical on-disk reset pattern is `{ 0, 0xFFFFFFFF, 0 }`.
/// 
/// `raw` preserves the payload verbatim so non-12-byte variants
/// (if any exist in other games) still roundtrip byte-exactly; the
/// three named fields are convenience accessors over the common case.
/// `endian` is the wire endian the payload was read in — needed to
/// decode the `u32` accessors for X360 / BE tags.
#[pyclass(name = "ApiInteropData", module = "blam_tags")]
pub struct PyApiInteropData(pub blam_tags::fields::ApiInteropData);

#[pymethods]
impl PyApiInteropData {
    #[getter(raw)]
    fn get_raw(&self) -> Vec<u8> { self.0.raw.clone() }
    #[setter(raw)]
    fn set_raw(&mut self, value: Vec<u8>) { self.0.raw = value; }
    #[getter(endian)]
    fn get_endian(&self) -> PyEndian { PyEndian::from(self.0.endian) }
    #[setter(endian)]
    fn set_endian(&mut self, value: PyEndian) { self.0.endian = blam_tags::io::Endian::from(value); }
    #[new]
    fn new(raw: Vec<u8>, endian: PyEndian) -> Self { Self(blam_tags::fields::ApiInteropData { raw: raw, endian: blam_tags::io::Endian::from(endian) }) }
    /// Parse a `ti][` payload (header already consumed). `endian` is
    /// the file's wire endian; the raw bytes are preserved verbatim.
    #[staticmethod]
    fn from_bytes(payload: Vec<u8>, endian: PyEndian) -> PyApiInteropData { PyApiInteropData(blam_tags::fields::ApiInteropData::from_bytes(&payload, blam_tags::io::Endian::from(endian))) }
    /// Serialize back to a `ti][` payload (caller writes the header).
    fn to_bytes(&self) -> Vec<u8> { self.0.to_bytes() }
    /// Reset pattern BCS writes on save: `{ descriptor=0,
    /// address=UINT_MAX, definition_address=0 }`. 12 bytes, LE.
    #[staticmethod]
    fn reset() -> PyApiInteropData { PyApiInteropData(blam_tags::fields::ApiInteropData::reset()) }
    /// `descriptor` field (u32 at offset 0), if the payload has the
    /// canonical 12-byte shape.
    fn descriptor(&self) -> Option<u32> { self.0.descriptor() }
    /// `address` field (u32 at offset 4), if the payload has the
    /// canonical 12-byte shape.
    fn address(&self) -> Option<u32> { self.0.address() }
    /// `definition_address` field (u32 at offset 8), if the payload
    /// has the canonical 12-byte shape.
    fn definition_address(&self) -> Option<u32> { self.0.definition_address() }
    fn __repr__(&self) -> String { "<ApiInteropData object>".to_string() }
}

/// 8-bit-per-channel ARGB color, packed into a single `u32`. The engine
/// accesses each channel via bit shifts / masks — this is deliberately
/// not split into separate byte fields to match the on-disk layout.
#[pyclass(name = "ArgbColor", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyArgbColor(pub blam_tags::math::ArgbColor);

#[pymethods]
impl PyArgbColor {
    #[getter(value)]
    fn get_value(&self) -> u32 { self.0.0 }
    #[setter(value)]
    fn set_value(&mut self, value: u32) { self.0.0 = value; }
    #[new]
    fn new(value: u32) -> Self { Self(blam_tags::math::ArgbColor(value)) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// Wire byte order. Carried at the top of every read function so the
/// dispatching primitive helpers ([`read_u16`], [`read_u32`], etc.)
/// pick the right `from_le_bytes` / `from_be_bytes` path.
/// 
/// Detected once per file in [`crate::TagFile::read`] by peeking the
/// fixed `BLAM` signature in both orientations, then threaded through
/// the entire read tree. The value is also stored on the parsed
/// [`crate::TagFile`] so writers (later) can round-trip the same
/// endian.
#[pyclass(name = "Endian", module = "blam_tags", from_py_object, eq, eq_int, frozen)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum PyEndian {
    Le,
    Be,
}

impl From<blam_tags::io::Endian> for PyEndian {
    fn from(v: blam_tags::io::Endian) -> Self {
        match v {
            blam_tags::io::Endian::Le => Self::Le,
            blam_tags::io::Endian::Be => Self::Be,
        }
    }
}

impl From<PyEndian> for blam_tags::io::Endian {
    fn from(v: PyEndian) -> Self {
        match v {
            PyEndian::Le => Self::Le,
            PyEndian::Be => Self::Be,
        }
    }
}

#[pymethods]
impl PyEndian {
    fn __repr__(&self) -> String { format!("{:?}", blam_tags::io::Endian::from(*self)) }
}

/// The Halo game (engine generation) a tag belongs to.
#[pyclass(name = "Game", module = "blam_tags", from_py_object, eq, eq_int, frozen)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum PyGame {
    Halo1,
    Halo2,
    Halo3,
}

impl From<blam_tags::game::Game> for PyGame {
    fn from(v: blam_tags::game::Game) -> Self {
        match v {
            blam_tags::game::Game::Halo1 => Self::Halo1,
            blam_tags::game::Game::Halo2 => Self::Halo2,
            blam_tags::game::Game::Halo3 => Self::Halo3,
        }
    }
}

impl From<PyGame> for blam_tags::game::Game {
    fn from(v: PyGame) -> Self {
        match v {
            PyGame::Halo1 => Self::Halo1,
            PyGame::Halo2 => Self::Halo2,
            PyGame::Halo3 => Self::Halo3,
        }
    }
}

#[pymethods]
impl PyGame {
    /// Classify a tag by its container engine: classic Halo CE → Halo1,
    /// classic Halo 2 (any sub-version) → Halo2, MCC self-describing →
    /// Halo3.
    #[staticmethod]
    fn of(tag: &PyTagFile) -> PyGame { PyGame::from(blam_tags::game::Game::of(&tag.0)) }
    /// The JMS text-format version this game's tools read/write.
    fn jms_version(&self) -> u16 { blam_tags::game::Game::from(*self).jms_version() }
    /// The ASS text-format version, or `None` for Halo 1 (no ASS format —
    /// Halo 1 BSP source is JMS).
    fn ass_version(&self) -> Option<u16> { blam_tags::game::Game::from(*self).ass_version() }
    /// The JMA-family (animation) text-format version this game's tools
    /// read/write.
    /// 
    /// Unlike JMS/ASS, all three generations share version **16392** —
    /// the `header + node{name,first_child,next_sibling} + per-frame
    /// transforms` layout. HABT (`io_scene_halo/file_jma`) lists 16392 as
    /// valid for CE/H2/H3 (`__init__.py`: `16390` = "CE/H2/H3"), and our
    /// writer already emits 16392 with H3+Reach corpus validation. The
    /// later `16395` H2/H3 variant only adds an optional biped-controller
    /// transform block, which extraction doesn't need; keeping one version
    /// per game here gives a single dispatch point should that change.
    fn jma_version(&self) -> u16 { blam_tags::game::Game::from(*self).jma_version() }
    fn __repr__(&self) -> String { format!("{:?}", blam_tags::game::Game::from(*self)) }
}

/// A 4×4 transform matrix, row-major (`m[row][col]`), applied to column
/// vectors (`M * v`) — the same convention as Blender's `mathutils.Matrix`
/// (so `A * B` then decompose matches Foundry's `A @ B`). Used for the
/// object-space pose-overlay corrections, which need full forward-kinematic
/// matrices (translation + rotation + uniform scale) per bone.
#[pyclass(name = "Matrix4", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyMatrix4(pub blam_tags::math::Matrix4);

#[pymethods]
impl PyMatrix4 {
    #[getter(m)]
    fn get_m(&self) -> Vec<Vec<f32>> { self.0.m.to_vec().into_iter().map(|v| v.to_vec()).collect() }
    #[setter(m)]
    fn set_m(&mut self, value: Vec<Vec<f32>>) -> PyResult<()> { self.0.m = __seq_to_array::<_, 4>(value.into_iter().map(|v| Ok(__seq_to_array::<_, 4>(v)?)).collect::<PyResult<Vec<_>>>()?)?; Ok(()) }
    #[new]
    fn new(m: Vec<Vec<f32>>) -> PyResult<Self> { Ok(Self(blam_tags::math::Matrix4 { m: __seq_to_array::<_, 4>(m.into_iter().map(|v| Ok(__seq_to_array::<_, 4>(v)?)).collect::<PyResult<Vec<_>>>()?)? })) }
    #[classattr]
    #[allow(non_snake_case)]
    fn IDENTITY() -> Self { Self(blam_tags::math::Matrix4::IDENTITY) }
    /// The translation column (`m[*][3]`).
    fn translation(&self) -> Vec<f32> { self.0.translation().to_vec() }
    /// Build `T * R * S` from a translation, rotation quaternion and a
    /// **uniform** scale — Blender's `Matrix.LocRotScale(loc, rot,
    /// Vector.Fill(3, scale))`.
    #[staticmethod]
    fn from_loc_rot_scale(t: PyRealPoint3d, q: PyRealQuaternion, s: f32) -> PyMatrix4 { PyMatrix4(blam_tags::math::Matrix4::from_loc_rot_scale(t.0, q.0, s)) }
    /// Affine inverse. Assumes the bottom row is `[0,0,0,1]` (always true
    /// for products of `from_loc_rot_scale` matrices). Inverts the upper
    /// 3×3 via its adjugate and back-transforms the translation.
    fn inverse(&self) -> PyMatrix4 { PyMatrix4(self.0.inverse()) }
    /// Decompose into `(translation, rotation, uniform_scale)`. The
    /// uniform scale is the mean of the three column lengths (mirrors
    /// Foundry's `(scale.x + scale.y + scale.z) / 3`).
    fn decompose(&self) -> (PyRealPoint3d, PyRealQuaternion, f32) { (PyRealPoint3d(self.0.decompose().0), PyRealQuaternion(self.0.decompose().1), self.0.decompose().2) }
    fn __mul__(&self, rhs: PyMatrix4) -> PyMatrix4 { PyMatrix4(self.0 * rhs.0) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 2D point (integer).
#[pyclass(name = "Point2d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyPoint2d(pub blam_tags::math::Point2d);

#[pymethods]
impl PyPoint2d {
    #[getter(x)]
    fn get_x(&self) -> i16 { self.0.x }
    #[setter(x)]
    fn set_x(&mut self, value: i16) { self.0.x = value; }
    #[getter(y)]
    fn get_y(&self) -> i16 { self.0.y }
    #[setter(y)]
    fn set_y(&mut self, value: i16) { self.0.y = value; }
    #[new]
    fn new(x: i16, y: i16) -> Self { Self(blam_tags::math::Point2d { x: x, y: y }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// AHSV color (float).
#[pyclass(name = "RealAhsvColor", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealAhsvColor(pub blam_tags::math::RealAhsvColor);

#[pymethods]
impl PyRealAhsvColor {
    #[getter(alpha)]
    fn get_alpha(&self) -> f32 { self.0.alpha }
    #[setter(alpha)]
    fn set_alpha(&mut self, value: f32) { self.0.alpha = value; }
    #[getter(hue)]
    fn get_hue(&self) -> f32 { self.0.hue }
    #[setter(hue)]
    fn set_hue(&mut self, value: f32) { self.0.hue = value; }
    #[getter(saturation)]
    fn get_saturation(&self) -> f32 { self.0.saturation }
    #[setter(saturation)]
    fn set_saturation(&mut self, value: f32) { self.0.saturation = value; }
    #[getter(value)]
    fn get_value(&self) -> f32 { self.0.value }
    #[setter(value)]
    fn set_value(&mut self, value: f32) { self.0.value = value; }
    #[new]
    fn new(alpha: f32, hue: f32, saturation: f32, value: f32) -> Self { Self(blam_tags::math::RealAhsvColor { alpha: alpha, hue: hue, saturation: saturation, value: value }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// ARGB color (float, 0.0–1.0).
#[pyclass(name = "RealArgbColor", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealArgbColor(pub blam_tags::math::RealArgbColor);

#[pymethods]
impl PyRealArgbColor {
    #[getter(alpha)]
    fn get_alpha(&self) -> f32 { self.0.alpha }
    #[setter(alpha)]
    fn set_alpha(&mut self, value: f32) { self.0.alpha = value; }
    #[getter(red)]
    fn get_red(&self) -> f32 { self.0.red }
    #[setter(red)]
    fn set_red(&mut self, value: f32) { self.0.red = value; }
    #[getter(green)]
    fn get_green(&self) -> f32 { self.0.green }
    #[setter(green)]
    fn set_green(&mut self, value: f32) { self.0.green = value; }
    #[getter(blue)]
    fn get_blue(&self) -> f32 { self.0.blue }
    #[setter(blue)]
    fn set_blue(&mut self, value: f32) { self.0.blue = value; }
    #[new]
    fn new(alpha: f32, red: f32, green: f32, blue: f32) -> Self { Self(blam_tags::math::RealArgbColor { alpha: alpha, red: red, green: green, blue: blue }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// Bounds (min/max pair).
#[pyclass(name = "RealBounds", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealBounds(pub blam_tags::math::Bounds<f32>);

#[pymethods]
impl PyRealBounds {
    #[getter(lower)]
    fn get_lower(&self) -> f32 { self.0.lower }
    #[setter(lower)]
    fn set_lower(&mut self, value: f32) { self.0.lower = value; }
    #[getter(upper)]
    fn get_upper(&self) -> f32 { self.0.upper }
    #[setter(upper)]
    fn set_upper(&mut self, value: f32) { self.0.upper = value; }
    #[new]
    fn new(lower: f32, upper: f32) -> Self { Self(blam_tags::math::Bounds::<f32> { lower: lower, upper: upper }) }
    /// `true` iff `value` lies on the closed interval `[lower, upper]`.
    fn contains(&self, value: f32) -> bool { self.0.contains(value) }
    /// `upper - lower`. Negative if the bounds are inverted.
    fn range(&self) -> f32 { self.0.range() }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 2D euler angles.
#[pyclass(name = "RealEulerAngles2d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealEulerAngles2d(pub blam_tags::math::RealEulerAngles2d);

#[pymethods]
impl PyRealEulerAngles2d {
    #[getter(yaw)]
    fn get_yaw(&self) -> f32 { self.0.yaw }
    #[setter(yaw)]
    fn set_yaw(&mut self, value: f32) { self.0.yaw = value; }
    #[getter(pitch)]
    fn get_pitch(&self) -> f32 { self.0.pitch }
    #[setter(pitch)]
    fn set_pitch(&mut self, value: f32) { self.0.pitch = value; }
    #[new]
    fn new(yaw: f32, pitch: f32) -> Self { Self(blam_tags::math::RealEulerAngles2d { yaw: yaw, pitch: pitch }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 3D euler angles.
#[pyclass(name = "RealEulerAngles3d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealEulerAngles3d(pub blam_tags::math::RealEulerAngles3d);

#[pymethods]
impl PyRealEulerAngles3d {
    #[getter(yaw)]
    fn get_yaw(&self) -> f32 { self.0.yaw }
    #[setter(yaw)]
    fn set_yaw(&mut self, value: f32) { self.0.yaw = value; }
    #[getter(pitch)]
    fn get_pitch(&self) -> f32 { self.0.pitch }
    #[setter(pitch)]
    fn set_pitch(&mut self, value: f32) { self.0.pitch = value; }
    #[getter(roll)]
    fn get_roll(&self) -> f32 { self.0.roll }
    #[setter(roll)]
    fn set_roll(&mut self, value: f32) { self.0.roll = value; }
    #[new]
    fn new(yaw: f32, pitch: f32, roll: f32) -> Self { Self(blam_tags::math::RealEulerAngles3d { yaw: yaw, pitch: pitch, roll: roll }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// HSV color (float).
#[pyclass(name = "RealHsvColor", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealHsvColor(pub blam_tags::math::RealHsvColor);

#[pymethods]
impl PyRealHsvColor {
    #[getter(hue)]
    fn get_hue(&self) -> f32 { self.0.hue }
    #[setter(hue)]
    fn set_hue(&mut self, value: f32) { self.0.hue = value; }
    #[getter(saturation)]
    fn get_saturation(&self) -> f32 { self.0.saturation }
    #[setter(saturation)]
    fn set_saturation(&mut self, value: f32) { self.0.saturation = value; }
    #[getter(value)]
    fn get_value(&self) -> f32 { self.0.value }
    #[setter(value)]
    fn set_value(&mut self, value: f32) { self.0.value = value; }
    #[new]
    fn new(hue: f32, saturation: f32, value: f32) -> Self { Self(blam_tags::math::RealHsvColor { hue: hue, saturation: saturation, value: value }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// `real_matrix4x3` — engine source `math/real_math.h:198-215` (52 B).
/// 
/// Affine TRS-style transform. Engine layout: `scale` at +0, then 3 basis
/// vectors (`forward`/`left`/`up`, each `real_vector3d` = 12 B), then
/// `position` (`real_point3d`, 12 B). Inner union with `n[4][3]` /
/// `matrix3x3` / `basis[3]+origin` — same bytes, different views; we expose
/// only the named-field form because the union views are aliases over the
/// same bytes and Rust callers can recompute them trivially.
#[pyclass(name = "RealMatrix4x3", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealMatrix4x3(pub blam_tags::math::RealMatrix4x3);

#[pymethods]
impl PyRealMatrix4x3 {
    #[getter(scale)]
    fn get_scale(&self) -> f32 { self.0.scale }
    #[setter(scale)]
    fn set_scale(&mut self, value: f32) { self.0.scale = value; }
    #[getter(forward)]
    fn get_forward(&self) -> PyRealVector3d { PyRealVector3d(self.0.forward) }
    #[setter(forward)]
    fn set_forward(&mut self, value: PyRealVector3d) { self.0.forward = value.0; }
    #[getter(left)]
    fn get_left(&self) -> PyRealVector3d { PyRealVector3d(self.0.left) }
    #[setter(left)]
    fn set_left(&mut self, value: PyRealVector3d) { self.0.left = value.0; }
    #[getter(up)]
    fn get_up(&self) -> PyRealVector3d { PyRealVector3d(self.0.up) }
    #[setter(up)]
    fn set_up(&mut self, value: PyRealVector3d) { self.0.up = value.0; }
    #[getter(position)]
    fn get_position(&self) -> PyRealPoint3d { PyRealPoint3d(self.0.position) }
    #[setter(position)]
    fn set_position(&mut self, value: PyRealPoint3d) { self.0.position = value.0; }
    #[new]
    fn new(scale: f32, forward: PyRealVector3d, left: PyRealVector3d, up: PyRealVector3d, position: PyRealPoint3d) -> Self { Self(blam_tags::math::RealMatrix4x3 { scale: scale, forward: forward.0, left: left.0, up: up.0, position: position.0 }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// Engine `real_orientation` (`math/real_math.h`, 32 bytes). A
/// quaternion+point+scale triplet — the canonical "local TRS in one
/// struct" used by the animation system. Stored verbatim in
/// `render_model.runtime_node_orientations!` (one entry per node, the
/// bind-pose snapshot tool.exe bakes at cache-compile time) and copied
/// into per-object `node_orientations` buffers at spawn.
/// 
/// Layout (matches engine `real_orientation`):
/// - `rotation` (quat) @ +0  (16 bytes)
/// - `translation` (point) @ +0x10 (12 bytes)
/// - `scale` (f32) @ +0x1C (4 bytes)
#[pyclass(name = "RealOrientation", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealOrientation(pub blam_tags::math::RealOrientation);

#[pymethods]
impl PyRealOrientation {
    #[getter(rotation)]
    fn get_rotation(&self) -> PyRealQuaternion { PyRealQuaternion(self.0.rotation) }
    #[setter(rotation)]
    fn set_rotation(&mut self, value: PyRealQuaternion) { self.0.rotation = value.0; }
    #[getter(translation)]
    fn get_translation(&self) -> PyRealPoint3d { PyRealPoint3d(self.0.translation) }
    #[setter(translation)]
    fn set_translation(&mut self, value: PyRealPoint3d) { self.0.translation = value.0; }
    #[getter(scale)]
    fn get_scale(&self) -> f32 { self.0.scale }
    #[setter(scale)]
    fn set_scale(&mut self, value: f32) { self.0.scale = value; }
    #[new]
    fn new(rotation: PyRealQuaternion, translation: PyRealPoint3d, scale: f32) -> Self { Self(blam_tags::math::RealOrientation { rotation: rotation.0, translation: translation.0, scale: scale }) }
    #[classattr]
    #[allow(non_snake_case)]
    fn IDENTITY() -> Self { Self(blam_tags::math::RealOrientation::IDENTITY) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 2D plane.
#[pyclass(name = "RealPlane2d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealPlane2d(pub blam_tags::math::RealPlane2d);

#[pymethods]
impl PyRealPlane2d {
    #[getter(i)]
    fn get_i(&self) -> f32 { self.0.i }
    #[setter(i)]
    fn set_i(&mut self, value: f32) { self.0.i = value; }
    #[getter(j)]
    fn get_j(&self) -> f32 { self.0.j }
    #[setter(j)]
    fn set_j(&mut self, value: f32) { self.0.j = value; }
    #[getter(d)]
    fn get_d(&self) -> f32 { self.0.d }
    #[setter(d)]
    fn set_d(&mut self, value: f32) { self.0.d = value; }
    #[new]
    fn new(i: f32, j: f32, d: f32) -> Self { Self(blam_tags::math::RealPlane2d { i: i, j: j, d: d }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 3D plane.
#[pyclass(name = "RealPlane3d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealPlane3d(pub blam_tags::math::RealPlane3d);

#[pymethods]
impl PyRealPlane3d {
    #[getter(i)]
    fn get_i(&self) -> f32 { self.0.i }
    #[setter(i)]
    fn set_i(&mut self, value: f32) { self.0.i = value; }
    #[getter(j)]
    fn get_j(&self) -> f32 { self.0.j }
    #[setter(j)]
    fn set_j(&mut self, value: f32) { self.0.j = value; }
    #[getter(k)]
    fn get_k(&self) -> f32 { self.0.k }
    #[setter(k)]
    fn set_k(&mut self, value: f32) { self.0.k = value; }
    #[getter(d)]
    fn get_d(&self) -> f32 { self.0.d }
    #[setter(d)]
    fn set_d(&mut self, value: f32) { self.0.d = value; }
    #[new]
    fn new(i: f32, j: f32, k: f32, d: f32) -> Self { Self(blam_tags::math::RealPlane3d { i: i, j: j, k: k, d: d }) }
    /// Plane normal, as a vector.
    fn normal(&self) -> PyRealVector3d { PyRealVector3d(self.0.normal()) }
    /// Signed distance from the origin to the plane along the normal.
    /// Equivalent to `self.d`.
    fn offset(&self) -> f32 { self.0.offset() }
    /// Cramer's-rule intersection of three planes. Returns `None` if
    /// the planes don't meet at a single point (parallel planes,
    /// near-zero determinant).
    /// 
    /// Honors Halo's `n·p + d = 0` plane convention (as found in
    /// `real_plane_3d` tag fields). The solver solves
    /// `n_i · p = -d_i` for each plane.
    #[staticmethod]
    fn triple_intersection(a: PyRealPlane3d, b: PyRealPlane3d, c: PyRealPlane3d) -> Option<PyRealPoint3d> { blam_tags::math::RealPlane3d::triple_intersection(a.0, b.0, c.0).map(|v| PyRealPoint3d(v)) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 2D point (float).
#[pyclass(name = "RealPoint2d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealPoint2d(pub blam_tags::math::RealPoint2d);

#[pymethods]
impl PyRealPoint2d {
    #[getter(x)]
    fn get_x(&self) -> f32 { self.0.x }
    #[setter(x)]
    fn set_x(&mut self, value: f32) { self.0.x = value; }
    #[getter(y)]
    fn get_y(&self) -> f32 { self.0.y }
    #[setter(y)]
    fn set_y(&mut self, value: f32) { self.0.y = value; }
    #[new]
    fn new(x: f32, y: f32) -> Self { Self(blam_tags::math::RealPoint2d { x: x, y: y }) }
    #[classattr]
    #[allow(non_snake_case)]
    fn ZERO() -> Self { Self(blam_tags::math::RealPoint2d::ZERO) }
    /// Treat this point's coordinates as a free vector. Useful when
    /// you need vector arithmetic on a coordinate triple that the
    /// schema modeled as a point.
    fn as_vector(&self) -> PyRealVector2d { PyRealVector2d(self.0.as_vector()) }
    /// Distance to another point.
    fn distance_to(&self, other: PyRealPoint2d) -> f32 { self.0.distance_to(other.0) }
    /// Squared distance to another point.
    fn distance_squared_to(&self, other: PyRealPoint2d) -> f32 { self.0.distance_squared_to(other.0) }
    /// Multiply every coordinate by `k`. Equivalent to `self * k`.
    fn scaled(&self, k: f32) -> PyRealPoint2d { PyRealPoint2d(self.0.scaled(k)) }
    /// Component pair `[x, y]`.
    fn to_array(&self) -> Vec<f32> { self.0.to_array().to_vec() }
    fn __add__(&self, rhs: PyRealVector2d) -> PyRealPoint2d { PyRealPoint2d(self.0 + rhs.0) }
    fn __mul__(&self, rhs: f32) -> PyRealPoint2d { PyRealPoint2d(self.0 * rhs) }
    fn __sub__<'py>(&self, rhs: &Bound<'py, PyAny>) -> PyResult<Bound<'py, PyAny>> {
        if let Ok(v) = rhs.extract::<PyRealPoint2d>() {
            return Ok(PyRealVector2d(self.0 - v.0).into_pyobject(rhs.py())?.into_any());
        }
        if let Ok(v) = rhs.extract::<PyRealVector2d>() {
            return Ok(PyRealPoint2d(self.0 - v.0).into_pyobject(rhs.py())?.into_any());
        }
        Err(pyo3::exceptions::PyTypeError::new_err("unsupported operand type for __sub__"))
    }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 3D point (float).
#[pyclass(name = "RealPoint3d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealPoint3d(pub blam_tags::math::RealPoint3d);

#[pymethods]
impl PyRealPoint3d {
    #[getter(x)]
    fn get_x(&self) -> f32 { self.0.x }
    #[setter(x)]
    fn set_x(&mut self, value: f32) { self.0.x = value; }
    #[getter(y)]
    fn get_y(&self) -> f32 { self.0.y }
    #[setter(y)]
    fn set_y(&mut self, value: f32) { self.0.y = value; }
    #[getter(z)]
    fn get_z(&self) -> f32 { self.0.z }
    #[setter(z)]
    fn set_z(&mut self, value: f32) { self.0.z = value; }
    #[new]
    fn new(x: f32, y: f32, z: f32) -> Self { Self(blam_tags::math::RealPoint3d { x: x, y: y, z: z }) }
    #[classattr]
    #[allow(non_snake_case)]
    fn ZERO() -> Self { Self(blam_tags::math::RealPoint3d::ZERO) }
    /// Treat this point's coordinates as a free vector. Useful when
    /// you need vector arithmetic on a coordinate triple that the
    /// schema modeled as a point — and for converting an offset that
    /// came in via `RealPoint3d` so it can feed [`RealQuaternion::rotate`]
    /// or vector-only operations.
    fn as_vector(&self) -> PyRealVector3d { PyRealVector3d(self.0.as_vector()) }
    /// Distance to another point.
    fn distance_to(&self, other: PyRealPoint3d) -> f32 { self.0.distance_to(other.0) }
    /// Squared distance to another point.
    fn distance_squared_to(&self, other: PyRealPoint3d) -> f32 { self.0.distance_squared_to(other.0) }
    /// Multiply every coordinate by `k`. Equivalent to `self * k`.
    fn scaled(&self, k: f32) -> PyRealPoint3d { PyRealPoint3d(self.0.scaled(k)) }
    /// Component triple `[x, y, z]`.
    fn to_array(&self) -> Vec<f32> { self.0.to_array().to_vec() }
    fn __add__(&self, rhs: PyRealVector3d) -> PyRealPoint3d { PyRealPoint3d(self.0 + rhs.0) }
    fn __mul__(&self, rhs: f32) -> PyRealPoint3d { PyRealPoint3d(self.0 * rhs) }
    fn __sub__<'py>(&self, rhs: &Bound<'py, PyAny>) -> PyResult<Bound<'py, PyAny>> {
        if let Ok(v) = rhs.extract::<PyRealPoint3d>() {
            return Ok(PyRealVector3d(self.0 - v.0).into_pyobject(rhs.py())?.into_any());
        }
        if let Ok(v) = rhs.extract::<PyRealVector3d>() {
            return Ok(PyRealPoint3d(self.0 - v.0).into_pyobject(rhs.py())?.into_any());
        }
        Err(pyo3::exceptions::PyTypeError::new_err("unsupported operand type for __sub__"))
    }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// Quaternion. **Note**: the derived `Default` returns the zero quat
/// `(0, 0, 0, 0)`, **not** the identity. Use [`RealQuaternion::IDENTITY`]
/// when you mean a no-op rotation.
#[pyclass(name = "RealQuaternion", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealQuaternion(pub blam_tags::math::RealQuaternion);

#[pymethods]
impl PyRealQuaternion {
    #[getter(i)]
    fn get_i(&self) -> f32 { self.0.i }
    #[setter(i)]
    fn set_i(&mut self, value: f32) { self.0.i = value; }
    #[getter(j)]
    fn get_j(&self) -> f32 { self.0.j }
    #[setter(j)]
    fn set_j(&mut self, value: f32) { self.0.j = value; }
    #[getter(k)]
    fn get_k(&self) -> f32 { self.0.k }
    #[setter(k)]
    fn set_k(&mut self, value: f32) { self.0.k = value; }
    #[getter(w)]
    fn get_w(&self) -> f32 { self.0.w }
    #[setter(w)]
    fn set_w(&mut self, value: f32) { self.0.w = value; }
    #[new]
    fn new(i: f32, j: f32, k: f32, w: f32) -> Self { Self(blam_tags::math::RealQuaternion { i: i, j: j, k: k, w: w }) }
    #[classattr]
    #[allow(non_snake_case)]
    fn IDENTITY() -> Self { Self(blam_tags::math::RealQuaternion::IDENTITY) }
    /// Component-wise dot product. Used by `nlerp` for short-arc
    /// detection (negative dot → flip one quat to take the shorter
    /// rotational path).
    fn dot(&self, other: PyRealQuaternion) -> f32 { self.0.dot(other.0) }
    /// Squared 4D length.
    fn length_squared(&self) -> f32 { self.0.length_squared() }
    /// 4D length.
    fn length(&self) -> f32 { self.0.length() }
    /// Unit-normalize. Mirrors `fast_quaternion_normalize` from the H3
    /// binary — divides by the magnitude. Returns the input unchanged
    /// on a zero-magnitude quat (no `1/0` blow-up; callers can detect
    /// the zero case by checking `i==j==k==w==0`).
    fn normalized(&self) -> PyRealQuaternion { PyRealQuaternion(self.0.normalized()) }
    /// Conjugate: negate the imaginary part, keep `w`. For unit
    /// quaternions this is the inverse rotation.
    fn conjugate(&self) -> PyRealQuaternion { PyRealQuaternion(self.0.conjugate()) }
    /// Construct from three column basis vectors of an orthonormal
    /// rotation matrix. Standard trace-and-largest-diagonal extraction.
    #[staticmethod]
    fn from_basis_columns(c0: PyRealVector3d, c1: PyRealVector3d, c2: PyRealVector3d) -> PyRealQuaternion { PyRealQuaternion(blam_tags::math::RealQuaternion::from_basis_columns(c0.0, c1.0, c2.0)) }
    /// Shortest-arc rotation between two unit vectors. Mirrors
    /// TagTool's `QuaternionFromVector` helper used in JMS phmo
    /// pill orientation. Degenerate cases (parallel or
    /// anti-parallel inputs) collapse to identity or a 180° rotation
    /// around an arbitrary perpendicular axis.
    #[staticmethod]
    fn shortest_arc(from: PyRealVector3d, to: PyRealVector3d) -> PyRealQuaternion { PyRealQuaternion(blam_tags::math::RealQuaternion::shortest_arc(from.0, to.0)) }
    /// Normalized linear interpolation, short-arc. If `self.dot(other) < 0`
    /// the second quat is flipped so the interpolation takes the shorter
    /// rotational path.
    fn nlerp(&self, other: PyRealQuaternion, t: f32) -> PyRealQuaternion { PyRealQuaternion(self.0.nlerp(other.0, t)) }
    /// Component quad `[i, j, k, w]`.
    fn to_array(&self) -> Vec<f32> { self.0.to_array().to_vec() }
    /// Apply this rotation to a vector. Optimized two-cross-product form:
    /// `v' = v + 2 * cross(q.xyz, cross(q.xyz, v) + q.w * v)`.
    fn rotate(&self, v: PyRealVector3d) -> PyRealVector3d { PyRealVector3d(self.0.rotate(v.0)) }
    fn __mul__<'py>(&self, rhs: &Bound<'py, PyAny>) -> PyResult<Bound<'py, PyAny>> {
        if let Ok(v) = rhs.extract::<PyRealQuaternion>() {
            return Ok(PyRealQuaternion(self.0 * v.0).into_pyobject(rhs.py())?.into_any());
        }
        if let Ok(v) = rhs.extract::<PyRealVector3d>() {
            return Ok(PyRealVector3d(self.0 * v.0).into_pyobject(rhs.py())?.into_any());
        }
        Err(pyo3::exceptions::PyTypeError::new_err("unsupported operand type for __mul__"))
    }
    fn __neg__(&self) -> PyRealQuaternion { PyRealQuaternion(-self.0) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// `real_rectangle2d` — engine source `math/real_math.h:239-250` (16 B).
/// 
/// Two intervals (`[x0,x1] × [y0,y1]`) packed as four floats. Engine uses
/// this for frustum bounds in screen / projection space.
#[pyclass(name = "RealRectangle2d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealRectangle2d(pub blam_tags::math::RealRectangle2d);

#[pymethods]
impl PyRealRectangle2d {
    #[getter(x0)]
    fn get_x0(&self) -> f32 { self.0.x0 }
    #[setter(x0)]
    fn set_x0(&mut self, value: f32) { self.0.x0 = value; }
    #[getter(x1)]
    fn get_x1(&self) -> f32 { self.0.x1 }
    #[setter(x1)]
    fn set_x1(&mut self, value: f32) { self.0.x1 = value; }
    #[getter(y0)]
    fn get_y0(&self) -> f32 { self.0.y0 }
    #[setter(y0)]
    fn set_y0(&mut self, value: f32) { self.0.y0 = value; }
    #[getter(y1)]
    fn get_y1(&self) -> f32 { self.0.y1 }
    #[setter(y1)]
    fn set_y1(&mut self, value: f32) { self.0.y1 = value; }
    #[new]
    fn new(x0: f32, x1: f32, y0: f32, y1: f32) -> Self { Self(blam_tags::math::RealRectangle2d { x0: x0, x1: x1, y0: y0, y1: y1 }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// `real_rectangle3d` — engine source `math/real_math.h:253-266` (24 B).
/// 
/// Three intervals (`[x0,x1] × [y0,y1] × [z0,z1]`).
#[pyclass(name = "RealRectangle3d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealRectangle3d(pub blam_tags::math::RealRectangle3d);

#[pymethods]
impl PyRealRectangle3d {
    #[getter(x0)]
    fn get_x0(&self) -> f32 { self.0.x0 }
    #[setter(x0)]
    fn set_x0(&mut self, value: f32) { self.0.x0 = value; }
    #[getter(x1)]
    fn get_x1(&self) -> f32 { self.0.x1 }
    #[setter(x1)]
    fn set_x1(&mut self, value: f32) { self.0.x1 = value; }
    #[getter(y0)]
    fn get_y0(&self) -> f32 { self.0.y0 }
    #[setter(y0)]
    fn set_y0(&mut self, value: f32) { self.0.y0 = value; }
    #[getter(y1)]
    fn get_y1(&self) -> f32 { self.0.y1 }
    #[setter(y1)]
    fn set_y1(&mut self, value: f32) { self.0.y1 = value; }
    #[getter(z0)]
    fn get_z0(&self) -> f32 { self.0.z0 }
    #[setter(z0)]
    fn set_z0(&mut self, value: f32) { self.0.z0 = value; }
    #[getter(z1)]
    fn get_z1(&self) -> f32 { self.0.z1 }
    #[setter(z1)]
    fn set_z1(&mut self, value: f32) { self.0.z1 = value; }
    #[new]
    fn new(x0: f32, x1: f32, y0: f32, y1: f32, z0: f32, z1: f32) -> Self { Self(blam_tags::math::RealRectangle3d { x0: x0, x1: x1, y0: y0, y1: y1, z0: z0, z1: z1 }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// RGB color (float, 0.0–1.0).
#[pyclass(name = "RealRgbColor", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealRgbColor(pub blam_tags::math::RealRgbColor);

#[pymethods]
impl PyRealRgbColor {
    #[getter(red)]
    fn get_red(&self) -> f32 { self.0.red }
    #[setter(red)]
    fn set_red(&mut self, value: f32) { self.0.red = value; }
    #[getter(green)]
    fn get_green(&self) -> f32 { self.0.green }
    #[setter(green)]
    fn set_green(&mut self, value: f32) { self.0.green = value; }
    #[getter(blue)]
    fn get_blue(&self) -> f32 { self.0.blue }
    #[setter(blue)]
    fn set_blue(&mut self, value: f32) { self.0.blue = value; }
    #[new]
    fn new(red: f32, green: f32, blue: f32) -> Self { Self(blam_tags::math::RealRgbColor { red: red, green: green, blue: blue }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 2D vector (float).
#[pyclass(name = "RealVector2d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealVector2d(pub blam_tags::math::RealVector2d);

#[pymethods]
impl PyRealVector2d {
    #[getter(i)]
    fn get_i(&self) -> f32 { self.0.i }
    #[setter(i)]
    fn set_i(&mut self, value: f32) { self.0.i = value; }
    #[getter(j)]
    fn get_j(&self) -> f32 { self.0.j }
    #[setter(j)]
    fn set_j(&mut self, value: f32) { self.0.j = value; }
    #[new]
    fn new(i: f32, j: f32) -> Self { Self(blam_tags::math::RealVector2d { i: i, j: j }) }
    #[classattr]
    #[allow(non_snake_case)]
    fn ZERO() -> Self { Self(blam_tags::math::RealVector2d::ZERO) }
    /// Dot product.
    fn dot(&self, other: PyRealVector2d) -> f32 { self.0.dot(other.0) }
    /// Squared Euclidean length.
    fn length_squared(&self) -> f32 { self.0.length_squared() }
    /// Euclidean length.
    fn length(&self) -> f32 { self.0.length() }
    /// Length-normalize, returning [`Self::ZERO`] for near-zero vectors
    /// rather than NaNs.
    fn normalized(&self) -> PyRealVector2d { PyRealVector2d(self.0.normalized()) }
    /// Reinterpret this vector's coordinates as a point.
    fn as_point(&self) -> PyRealPoint2d { PyRealPoint2d(self.0.as_point()) }
    /// Component pair `[i, j]`.
    fn to_array(&self) -> Vec<f32> { self.0.to_array().to_vec() }
    fn __add__(&self, rhs: PyRealVector2d) -> PyRealVector2d { PyRealVector2d(self.0 + rhs.0) }
    fn __mul__(&self, rhs: f32) -> PyRealVector2d { PyRealVector2d(self.0 * rhs) }
    fn __neg__(&self) -> PyRealVector2d { PyRealVector2d(-self.0) }
    fn __sub__(&self, rhs: PyRealVector2d) -> PyRealVector2d { PyRealVector2d(self.0 - rhs.0) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 3D vector (float).
#[pyclass(name = "RealVector3d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRealVector3d(pub blam_tags::math::RealVector3d);

#[pymethods]
impl PyRealVector3d {
    #[getter(i)]
    fn get_i(&self) -> f32 { self.0.i }
    #[setter(i)]
    fn set_i(&mut self, value: f32) { self.0.i = value; }
    #[getter(j)]
    fn get_j(&self) -> f32 { self.0.j }
    #[setter(j)]
    fn set_j(&mut self, value: f32) { self.0.j = value; }
    #[getter(k)]
    fn get_k(&self) -> f32 { self.0.k }
    #[setter(k)]
    fn set_k(&mut self, value: f32) { self.0.k = value; }
    #[new]
    fn new(i: f32, j: f32, k: f32) -> Self { Self(blam_tags::math::RealVector3d { i: i, j: j, k: k }) }
    #[classattr]
    #[allow(non_snake_case)]
    fn ZERO() -> Self { Self(blam_tags::math::RealVector3d::ZERO) }
    /// Dot product.
    fn dot(&self, other: PyRealVector3d) -> f32 { self.0.dot(other.0) }
    /// Cross product `self × other`.
    fn cross(&self, other: PyRealVector3d) -> PyRealVector3d { PyRealVector3d(self.0.cross(other.0)) }
    /// Squared Euclidean length.
    fn length_squared(&self) -> f32 { self.0.length_squared() }
    /// Euclidean length.
    fn length(&self) -> f32 { self.0.length() }
    /// Length-normalize, returning [`Self::ZERO`] for near-zero vectors
    /// rather than NaNs.
    fn normalized(&self) -> PyRealVector3d { PyRealVector3d(self.0.normalized()) }
    /// Reinterpret this vector's coordinates as a point. Useful when
    /// a vector arithmetic result needs to be stored in a point slot
    /// (the schema sometimes models offsets as `real_vector_3d` and
    /// the consuming struct as `real_point_3d`).
    fn as_point(&self) -> PyRealPoint3d { PyRealPoint3d(self.0.as_point()) }
    /// Component triple `[i, j, k]`. Convenient for piping into
    /// generic writers that expect a slice of floats.
    fn to_array(&self) -> Vec<f32> { self.0.to_array().to_vec() }
    fn __add__(&self, rhs: PyRealVector3d) -> PyRealVector3d { PyRealVector3d(self.0 + rhs.0) }
    fn __mul__(&self, rhs: f32) -> PyRealVector3d { PyRealVector3d(self.0 * rhs) }
    fn __neg__(&self) -> PyRealVector3d { PyRealVector3d(-self.0) }
    fn __sub__(&self, rhs: PyRealVector3d) -> PyRealVector3d { PyRealVector3d(self.0 - rhs.0) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 2D rectangle (integer).
#[pyclass(name = "Rectangle2d", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRectangle2d(pub blam_tags::math::Rectangle2d);

#[pymethods]
impl PyRectangle2d {
    #[getter(top)]
    fn get_top(&self) -> i16 { self.0.top }
    #[setter(top)]
    fn set_top(&mut self, value: i16) { self.0.top = value; }
    #[getter(left)]
    fn get_left(&self) -> i16 { self.0.left }
    #[setter(left)]
    fn set_left(&mut self, value: i16) { self.0.left = value; }
    #[getter(bottom)]
    fn get_bottom(&self) -> i16 { self.0.bottom }
    #[setter(bottom)]
    fn set_bottom(&mut self, value: i16) { self.0.bottom = value; }
    #[getter(right)]
    fn get_right(&self) -> i16 { self.0.right }
    #[setter(right)]
    fn set_right(&mut self, value: i16) { self.0.right = value; }
    #[new]
    fn new(top: i16, left: i16, bottom: i16, right: i16) -> Self { Self(blam_tags::math::Rectangle2d { top: top, left: left, bottom: bottom, right: right }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// 8-bit-per-channel RGB color, packed into a single `u32`. The engine
/// accesses each channel via bit shifts / masks — this is deliberately
/// not split into separate byte fields to match the on-disk layout.
#[pyclass(name = "RgbColor", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyRgbColor(pub blam_tags::math::RgbColor);

#[pymethods]
impl PyRgbColor {
    #[getter(value)]
    fn get_value(&self) -> u32 { self.0.0 }
    #[setter(value)]
    fn set_value(&mut self, value: u32) { self.0.0 = value; }
    #[new]
    fn new(value: u32) -> Self { Self(blam_tags::math::RgbColor(value)) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// Bounds (min/max pair).
#[pyclass(name = "ShortBounds", module = "blam_tags", from_py_object, eq)]
#[derive(Clone, Copy, PartialEq)]
pub struct PyShortBounds(pub blam_tags::math::Bounds<i16>);

#[pymethods]
impl PyShortBounds {
    #[getter(lower)]
    fn get_lower(&self) -> i16 { self.0.lower }
    #[setter(lower)]
    fn set_lower(&mut self, value: i16) { self.0.lower = value; }
    #[getter(upper)]
    fn get_upper(&self) -> i16 { self.0.upper }
    #[setter(upper)]
    fn set_upper(&mut self, value: i16) { self.0.upper = value; }
    #[new]
    fn new(lower: i16, upper: i16) -> Self { Self(blam_tags::math::Bounds::<i16> { lower: lower, upper: upper }) }
    fn __repr__(&self) -> String { format!("{:?}", self.0) }
    fn __copy__(&self) -> Self { *self }
}

/// Parsed form of a `tgsi` string-id chunk payload. Used for both
/// [`TagFieldType::StringId`] and [`TagFieldType::OldStringId`].
/// Empty content represents `string_id::NONE`.
#[pyclass(name = "StringIdData", module = "blam_tags")]
pub struct PyStringIdData(pub blam_tags::fields::StringIdData);

#[pymethods]
impl PyStringIdData {
    #[getter(string)]
    fn get_string(&self) -> String { self.0.string.to_string() }
    #[setter(string)]
    fn set_string(&mut self, value: String) { self.0.string = value; }
    #[new]
    fn new(string: String) -> Self { Self(blam_tags::fields::StringIdData { string: string }) }
    /// Parse a `tgsi` payload (header already consumed).
    #[staticmethod]
    fn from_bytes(payload: Vec<u8>) -> PyStringIdData { PyStringIdData(blam_tags::fields::StringIdData::from_bytes(&payload)) }
    /// Serialize back to a `tgsi` payload (caller writes the header).
    fn to_bytes(&self) -> Vec<u8> { self.0.to_bytes() }
    fn __repr__(&self) -> String { "<StringIdData object>".to_string() }
}

/// Resolved type of a layout field.
/// 
/// Computed once per [`crate::layout::TagFieldLayout`] during
/// [`crate::layout::TagLayout::read`] by [`TagFieldType::from_name`], so
/// the hot read/write paths can dispatch on an enum instead of comparing
/// type-name strings on every field.
/// 
/// Variant names mirror the Halo type-name strings (e.g. `"real point 3d"
/// → RealPoint3d`). `Unknown` is the fallback for any unrecognized name
/// and also the initial value before resolution.
#[pyclass(name = "TagFieldType", module = "blam_tags", from_py_object, eq, eq_int, frozen)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum PyTagFieldType {
    Unknown,
    String,
    LongString,
    StringId,
    OldStringId,
    CharInteger,
    ShortInteger,
    LongInteger,
    Int64Integer,
    ByteInteger,
    WordInteger,
    DwordInteger,
    QwordInteger,
    Angle,
    Tag,
    CharEnum,
    ShortEnum,
    LongEnum,
    LongFlags,
    WordFlags,
    ByteFlags,
    Point2d,
    Rectangle2d,
    RgbColor,
    ArgbColor,
    Real,
    RealSlider,
    RealFraction,
    RealPoint2d,
    RealPoint3d,
    RealVector2d,
    RealVector3d,
    RealQuaternion,
    RealEulerAngles2d,
    RealEulerAngles3d,
    RealPlane2d,
    RealPlane3d,
    RealRgbColor,
    RealArgbColor,
    RealHsvColor,
    RealAhsvColor,
    ShortIntegerBounds,
    AngleBounds,
    RealBounds,
    FractionBounds,
    TagReference,
    Block,
    LongBlockFlags,
    WordBlockFlags,
    ByteBlockFlags,
    CharBlockIndex,
    CustomCharBlockIndex,
    ShortBlockIndex,
    CustomShortBlockIndex,
    LongBlockIndex,
    CustomLongBlockIndex,
    Data,
    VertexBuffer,
    Pointer,
    RealMatrix3x3,
    Pad,
    UselessPad,
    Skip,
    Explanation,
    Custom,
    Struct,
    Array,
    PageableResource,
    ApiInterop,
    Terminator,
    NonCacheRuntimeValue,
}

impl From<blam_tags::fields::TagFieldType> for PyTagFieldType {
    fn from(v: blam_tags::fields::TagFieldType) -> Self {
        match v {
            blam_tags::fields::TagFieldType::Unknown => Self::Unknown,
            blam_tags::fields::TagFieldType::String => Self::String,
            blam_tags::fields::TagFieldType::LongString => Self::LongString,
            blam_tags::fields::TagFieldType::StringId => Self::StringId,
            blam_tags::fields::TagFieldType::OldStringId => Self::OldStringId,
            blam_tags::fields::TagFieldType::CharInteger => Self::CharInteger,
            blam_tags::fields::TagFieldType::ShortInteger => Self::ShortInteger,
            blam_tags::fields::TagFieldType::LongInteger => Self::LongInteger,
            blam_tags::fields::TagFieldType::Int64Integer => Self::Int64Integer,
            blam_tags::fields::TagFieldType::ByteInteger => Self::ByteInteger,
            blam_tags::fields::TagFieldType::WordInteger => Self::WordInteger,
            blam_tags::fields::TagFieldType::DwordInteger => Self::DwordInteger,
            blam_tags::fields::TagFieldType::QwordInteger => Self::QwordInteger,
            blam_tags::fields::TagFieldType::Angle => Self::Angle,
            blam_tags::fields::TagFieldType::Tag => Self::Tag,
            blam_tags::fields::TagFieldType::CharEnum => Self::CharEnum,
            blam_tags::fields::TagFieldType::ShortEnum => Self::ShortEnum,
            blam_tags::fields::TagFieldType::LongEnum => Self::LongEnum,
            blam_tags::fields::TagFieldType::LongFlags => Self::LongFlags,
            blam_tags::fields::TagFieldType::WordFlags => Self::WordFlags,
            blam_tags::fields::TagFieldType::ByteFlags => Self::ByteFlags,
            blam_tags::fields::TagFieldType::Point2d => Self::Point2d,
            blam_tags::fields::TagFieldType::Rectangle2d => Self::Rectangle2d,
            blam_tags::fields::TagFieldType::RgbColor => Self::RgbColor,
            blam_tags::fields::TagFieldType::ArgbColor => Self::ArgbColor,
            blam_tags::fields::TagFieldType::Real => Self::Real,
            blam_tags::fields::TagFieldType::RealSlider => Self::RealSlider,
            blam_tags::fields::TagFieldType::RealFraction => Self::RealFraction,
            blam_tags::fields::TagFieldType::RealPoint2d => Self::RealPoint2d,
            blam_tags::fields::TagFieldType::RealPoint3d => Self::RealPoint3d,
            blam_tags::fields::TagFieldType::RealVector2d => Self::RealVector2d,
            blam_tags::fields::TagFieldType::RealVector3d => Self::RealVector3d,
            blam_tags::fields::TagFieldType::RealQuaternion => Self::RealQuaternion,
            blam_tags::fields::TagFieldType::RealEulerAngles2d => Self::RealEulerAngles2d,
            blam_tags::fields::TagFieldType::RealEulerAngles3d => Self::RealEulerAngles3d,
            blam_tags::fields::TagFieldType::RealPlane2d => Self::RealPlane2d,
            blam_tags::fields::TagFieldType::RealPlane3d => Self::RealPlane3d,
            blam_tags::fields::TagFieldType::RealRgbColor => Self::RealRgbColor,
            blam_tags::fields::TagFieldType::RealArgbColor => Self::RealArgbColor,
            blam_tags::fields::TagFieldType::RealHsvColor => Self::RealHsvColor,
            blam_tags::fields::TagFieldType::RealAhsvColor => Self::RealAhsvColor,
            blam_tags::fields::TagFieldType::ShortIntegerBounds => Self::ShortIntegerBounds,
            blam_tags::fields::TagFieldType::AngleBounds => Self::AngleBounds,
            blam_tags::fields::TagFieldType::RealBounds => Self::RealBounds,
            blam_tags::fields::TagFieldType::FractionBounds => Self::FractionBounds,
            blam_tags::fields::TagFieldType::TagReference => Self::TagReference,
            blam_tags::fields::TagFieldType::Block => Self::Block,
            blam_tags::fields::TagFieldType::LongBlockFlags => Self::LongBlockFlags,
            blam_tags::fields::TagFieldType::WordBlockFlags => Self::WordBlockFlags,
            blam_tags::fields::TagFieldType::ByteBlockFlags => Self::ByteBlockFlags,
            blam_tags::fields::TagFieldType::CharBlockIndex => Self::CharBlockIndex,
            blam_tags::fields::TagFieldType::CustomCharBlockIndex => Self::CustomCharBlockIndex,
            blam_tags::fields::TagFieldType::ShortBlockIndex => Self::ShortBlockIndex,
            blam_tags::fields::TagFieldType::CustomShortBlockIndex => Self::CustomShortBlockIndex,
            blam_tags::fields::TagFieldType::LongBlockIndex => Self::LongBlockIndex,
            blam_tags::fields::TagFieldType::CustomLongBlockIndex => Self::CustomLongBlockIndex,
            blam_tags::fields::TagFieldType::Data => Self::Data,
            blam_tags::fields::TagFieldType::VertexBuffer => Self::VertexBuffer,
            blam_tags::fields::TagFieldType::Pointer => Self::Pointer,
            blam_tags::fields::TagFieldType::RealMatrix3x3 => Self::RealMatrix3x3,
            blam_tags::fields::TagFieldType::Pad => Self::Pad,
            blam_tags::fields::TagFieldType::UselessPad => Self::UselessPad,
            blam_tags::fields::TagFieldType::Skip => Self::Skip,
            blam_tags::fields::TagFieldType::Explanation => Self::Explanation,
            blam_tags::fields::TagFieldType::Custom => Self::Custom,
            blam_tags::fields::TagFieldType::Struct => Self::Struct,
            blam_tags::fields::TagFieldType::Array => Self::Array,
            blam_tags::fields::TagFieldType::PageableResource => Self::PageableResource,
            blam_tags::fields::TagFieldType::ApiInterop => Self::ApiInterop,
            blam_tags::fields::TagFieldType::Terminator => Self::Terminator,
            blam_tags::fields::TagFieldType::NonCacheRuntimeValue => Self::NonCacheRuntimeValue,
        }
    }
}

impl From<PyTagFieldType> for blam_tags::fields::TagFieldType {
    fn from(v: PyTagFieldType) -> Self {
        match v {
            PyTagFieldType::Unknown => Self::Unknown,
            PyTagFieldType::String => Self::String,
            PyTagFieldType::LongString => Self::LongString,
            PyTagFieldType::StringId => Self::StringId,
            PyTagFieldType::OldStringId => Self::OldStringId,
            PyTagFieldType::CharInteger => Self::CharInteger,
            PyTagFieldType::ShortInteger => Self::ShortInteger,
            PyTagFieldType::LongInteger => Self::LongInteger,
            PyTagFieldType::Int64Integer => Self::Int64Integer,
            PyTagFieldType::ByteInteger => Self::ByteInteger,
            PyTagFieldType::WordInteger => Self::WordInteger,
            PyTagFieldType::DwordInteger => Self::DwordInteger,
            PyTagFieldType::QwordInteger => Self::QwordInteger,
            PyTagFieldType::Angle => Self::Angle,
            PyTagFieldType::Tag => Self::Tag,
            PyTagFieldType::CharEnum => Self::CharEnum,
            PyTagFieldType::ShortEnum => Self::ShortEnum,
            PyTagFieldType::LongEnum => Self::LongEnum,
            PyTagFieldType::LongFlags => Self::LongFlags,
            PyTagFieldType::WordFlags => Self::WordFlags,
            PyTagFieldType::ByteFlags => Self::ByteFlags,
            PyTagFieldType::Point2d => Self::Point2d,
            PyTagFieldType::Rectangle2d => Self::Rectangle2d,
            PyTagFieldType::RgbColor => Self::RgbColor,
            PyTagFieldType::ArgbColor => Self::ArgbColor,
            PyTagFieldType::Real => Self::Real,
            PyTagFieldType::RealSlider => Self::RealSlider,
            PyTagFieldType::RealFraction => Self::RealFraction,
            PyTagFieldType::RealPoint2d => Self::RealPoint2d,
            PyTagFieldType::RealPoint3d => Self::RealPoint3d,
            PyTagFieldType::RealVector2d => Self::RealVector2d,
            PyTagFieldType::RealVector3d => Self::RealVector3d,
            PyTagFieldType::RealQuaternion => Self::RealQuaternion,
            PyTagFieldType::RealEulerAngles2d => Self::RealEulerAngles2d,
            PyTagFieldType::RealEulerAngles3d => Self::RealEulerAngles3d,
            PyTagFieldType::RealPlane2d => Self::RealPlane2d,
            PyTagFieldType::RealPlane3d => Self::RealPlane3d,
            PyTagFieldType::RealRgbColor => Self::RealRgbColor,
            PyTagFieldType::RealArgbColor => Self::RealArgbColor,
            PyTagFieldType::RealHsvColor => Self::RealHsvColor,
            PyTagFieldType::RealAhsvColor => Self::RealAhsvColor,
            PyTagFieldType::ShortIntegerBounds => Self::ShortIntegerBounds,
            PyTagFieldType::AngleBounds => Self::AngleBounds,
            PyTagFieldType::RealBounds => Self::RealBounds,
            PyTagFieldType::FractionBounds => Self::FractionBounds,
            PyTagFieldType::TagReference => Self::TagReference,
            PyTagFieldType::Block => Self::Block,
            PyTagFieldType::LongBlockFlags => Self::LongBlockFlags,
            PyTagFieldType::WordBlockFlags => Self::WordBlockFlags,
            PyTagFieldType::ByteBlockFlags => Self::ByteBlockFlags,
            PyTagFieldType::CharBlockIndex => Self::CharBlockIndex,
            PyTagFieldType::CustomCharBlockIndex => Self::CustomCharBlockIndex,
            PyTagFieldType::ShortBlockIndex => Self::ShortBlockIndex,
            PyTagFieldType::CustomShortBlockIndex => Self::CustomShortBlockIndex,
            PyTagFieldType::LongBlockIndex => Self::LongBlockIndex,
            PyTagFieldType::CustomLongBlockIndex => Self::CustomLongBlockIndex,
            PyTagFieldType::Data => Self::Data,
            PyTagFieldType::VertexBuffer => Self::VertexBuffer,
            PyTagFieldType::Pointer => Self::Pointer,
            PyTagFieldType::RealMatrix3x3 => Self::RealMatrix3x3,
            PyTagFieldType::Pad => Self::Pad,
            PyTagFieldType::UselessPad => Self::UselessPad,
            PyTagFieldType::Skip => Self::Skip,
            PyTagFieldType::Explanation => Self::Explanation,
            PyTagFieldType::Custom => Self::Custom,
            PyTagFieldType::Struct => Self::Struct,
            PyTagFieldType::Array => Self::Array,
            PyTagFieldType::PageableResource => Self::PageableResource,
            PyTagFieldType::ApiInterop => Self::ApiInterop,
            PyTagFieldType::Terminator => Self::Terminator,
            PyTagFieldType::NonCacheRuntimeValue => Self::NonCacheRuntimeValue,
        }
    }
}

#[pymethods]
impl PyTagFieldType {
    /// Parse a field-type name string (as stored in the layout's
    /// `string_data`) into the dispatch enum. Unknown names are
    /// tolerated and returned as [`TagFieldType::Unknown`] — this is
    /// how we detect new or unhandled type names without panicking.
    #[staticmethod]
    fn from_name(name: String) -> PyTagFieldType { PyTagFieldType::from(blam_tags::fields::TagFieldType::from_name(name.as_str())) }
    fn __repr__(&self) -> String { format!("{:?}", blam_tags::fields::TagFieldType::from(*self)) }
}

/// Fixed 64-byte preamble at the start of every tag file.
/// 
/// Layout: `pad[36] + build_version + build_number + version +
/// group_tag + group_version + checksum + signature`.
#[pyclass(name = "TagFileHeader", module = "blam_tags")]
pub struct PyTagFileHeader(pub blam_tags::file::TagFileHeader);

#[pymethods]
impl PyTagFileHeader {
    #[getter(pad)]
    fn get_pad(&self) -> Vec<u8> { self.0.pad.to_vec() }
    #[setter(pad)]
    fn set_pad(&mut self, value: Vec<u8>) -> PyResult<()> { self.0.pad = __seq_to_array::<_, 36>(value)?; Ok(()) }
    #[getter(build_version)]
    fn get_build_version(&self) -> i32 { self.0.build_version }
    #[setter(build_version)]
    fn set_build_version(&mut self, value: i32) { self.0.build_version = value; }
    #[getter(build_number)]
    fn get_build_number(&self) -> i32 { self.0.build_number }
    #[setter(build_number)]
    fn set_build_number(&mut self, value: i32) { self.0.build_number = value; }
    #[getter(version)]
    fn get_version(&self) -> u32 { self.0.version }
    #[setter(version)]
    fn set_version(&mut self, value: u32) { self.0.version = value; }
    #[getter(group_tag)]
    fn get_group_tag(&self) -> u32 { self.0.group_tag }
    #[setter(group_tag)]
    fn set_group_tag(&mut self, value: u32) { self.0.group_tag = value; }
    #[getter(group_version)]
    fn get_group_version(&self) -> u32 { self.0.group_version }
    #[setter(group_version)]
    fn set_group_version(&mut self, value: u32) { self.0.group_version = value; }
    #[getter(checksum)]
    fn get_checksum(&self) -> u32 { self.0.checksum }
    #[setter(checksum)]
    fn set_checksum(&mut self, value: u32) { self.0.checksum = value; }
    #[getter(signature)]
    fn get_signature(&self) -> u32 { self.0.signature }
    #[setter(signature)]
    fn set_signature(&mut self, value: u32) { self.0.signature = value; }
    #[new]
    fn new(pad: Vec<u8>, build_version: i32, build_number: i32, version: u32, group_tag: u32, group_version: u32, checksum: u32, signature: u32) -> PyResult<Self> { Ok(Self(blam_tags::file::TagFileHeader { pad: __seq_to_array::<_, 36>(pad)?, build_version: build_version, build_number: build_number, version: version, group_tag: group_tag, group_version: group_version, checksum: checksum, signature: signature })) }
    fn __repr__(&self) -> String { "<TagFileHeader object>".to_string() }
}

/// Parsed form of a `tgrf` tag-reference chunk payload.
/// 
/// A null reference (payload shorter than the 4-byte group tag) is
/// represented as `None`; a resolved reference is `Some((group_tag,
/// path))`, where `path` is the UTF-8 tag path relative to the tag
/// root. No explicit terminator — the path fills the rest of the chunk.
#[pyclass(name = "TagReferenceData", module = "blam_tags")]
pub struct PyTagReferenceData(pub blam_tags::fields::TagReferenceData);

#[pymethods]
impl PyTagReferenceData {
    #[getter(group_tag_and_name)]
    fn get_group_tag_and_name(&self) -> Option<(u32, String)> { self.0.group_tag_and_name.clone().map(|v| (v.0, v.1.to_string())) }
    #[setter(group_tag_and_name)]
    fn set_group_tag_and_name(&mut self, value: Option<(u32, String)>) { self.0.group_tag_and_name = value.map(|v| (v.0, v.1)); }
    #[new]
    fn new(group_tag_and_name: Option<(u32, String)>) -> Self { Self(blam_tags::fields::TagReferenceData { group_tag_and_name: group_tag_and_name.map(|v| (v.0, v.1)) }) }
    /// Parse a `tgrf` payload (header already consumed). The 4-byte
    /// group tag prefix is read in the file's wire endian; the rest
    /// is the UTF-8 path. Bad UTF-8 in the path is decoded lossily
    /// (U+FFFD replacement) — preserves well-formed-input roundtrip
    /// while making the parser safe to feed corrupt bytes.
    #[staticmethod]
    fn from_bytes(payload: Vec<u8>, endian: PyEndian) -> PyTagReferenceData { PyTagReferenceData(blam_tags::fields::TagReferenceData::from_bytes(&payload, blam_tags::io::Endian::from(endian))) }
    /// Serialize back to a `tgrf` payload (caller writes the header). The
    /// group FOURCC is emitted in the file's wire `endian`, mirroring
    /// [`Self::from_bytes`], so a re-serialized reference round-trips instead
    /// of reversing the tag class. Halo CE tags are big-endian and store the
    /// reference group forward on disk (`mod2`); a hardcoded little-endian
    /// write turned it into `2dom` the moment a reference was edited, which
    /// corrupted the on-disk tag and made reverse-dependency lookups miss. The
    /// path is re-emitted NUL-terminated (the terminator stripped by
    /// [`Self::from_bytes`]).
    fn to_bytes(&self, endian: PyEndian) -> Vec<u8> { self.0.to_bytes(blam_tags::io::Endian::from(endian)) }
    fn __repr__(&self) -> String { "<TagReferenceData object>".to_string() }
}

/// A specific MCC title / loaded editing kit, identified by its game-id
/// (the kit folder name, e.g. `"halo4_mcc"`).
/// 
/// This is a *different axis* from [`Game`]: [`Game`] is the tag-format
/// generation derived from the tag bytes, and H3, ODST, Reach, and H4 all share
/// `Game::Halo3` because their `render_model`/JMS/ASS structures are identical.
/// The title captures which of those engines is actually loaded — a distinction
/// the tag bytes don't encode, but that matters for engine details like the HDR
/// tonemap (H3/Reach use a cubic curve, H4 a Hable filmic). It comes from the
/// loading context (the editing kit), not the tag, so it's parsed from the
/// game-id string rather than `of(tag)`.
#[pyclass(name = "Title", module = "blam_tags", from_py_object, eq, eq_int, frozen)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum PyTitle {
    HaloCe,
    Halo2,
    Halo2A,
    Halo3,
    Halo3Odst,
    HaloReach,
    Halo4,
}

impl From<blam_tags::game::Title> for PyTitle {
    fn from(v: blam_tags::game::Title) -> Self {
        match v {
            blam_tags::game::Title::HaloCe => Self::HaloCe,
            blam_tags::game::Title::Halo2 => Self::Halo2,
            blam_tags::game::Title::Halo2A => Self::Halo2A,
            blam_tags::game::Title::Halo3 => Self::Halo3,
            blam_tags::game::Title::Halo3Odst => Self::Halo3Odst,
            blam_tags::game::Title::HaloReach => Self::HaloReach,
            blam_tags::game::Title::Halo4 => Self::Halo4,
        }
    }
}

impl From<PyTitle> for blam_tags::game::Title {
    fn from(v: PyTitle) -> Self {
        match v {
            PyTitle::HaloCe => Self::HaloCe,
            PyTitle::Halo2 => Self::Halo2,
            PyTitle::Halo2A => Self::Halo2A,
            PyTitle::Halo3 => Self::Halo3,
            PyTitle::Halo3Odst => Self::Halo3Odst,
            PyTitle::HaloReach => Self::HaloReach,
            PyTitle::Halo4 => Self::Halo4,
        }
    }
}

#[pymethods]
impl PyTitle {
    /// Parse an MCC game-id / editing-kit folder name (e.g. `"halo4_mcc"`).
    /// Returns `None` for an unrecognized id.
    #[staticmethod]
    fn from_game_id(id: String) -> Option<PyTitle> { blam_tags::game::Title::from_game_id(id.as_str()).map(|v| PyTitle::from(v)) }
    fn __repr__(&self) -> String { format!("{:?}", blam_tags::game::Title::from(*self)) }
}

/// Parse an ASCII group-tag string (1-4 chars, e.g. `"bipd"` or
/// `"mo"`) into the BE-packed `u32` form used on disk. Short tags are
/// right-padded with spaces to 4 bytes. Returns `None` if the input
/// is longer than 4 bytes. Inverse of [`format_group_tag`].
#[pyfunction]
pub fn parse_group_tag(s: String) -> Option<u32> { blam_tags::fields::parse_group_tag(s.as_str()) }

/// Render a 4-byte group tag (stored as a BE-packed `u32` with
/// trailing-space padding for short tags) as its ASCII form, with
/// trailing spaces and NULs stripped. Matches the convention used
/// throughout the tag-file wire format. Inverse of [`parse_group_tag`].
#[pyfunction]
pub fn format_group_tag(tag: u32) -> String { blam_tags::fields::format_group_tag(tag).to_string() }

/// Register every generated class on the extension module.
pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<PyApiInteropData>()?;
    m.add_class::<PyArgbColor>()?;
    m.add_class::<PyEndian>()?;
    m.add_class::<PyGame>()?;
    m.add_class::<PyMatrix4>()?;
    m.add_class::<PyPoint2d>()?;
    m.add_class::<PyRealAhsvColor>()?;
    m.add_class::<PyRealArgbColor>()?;
    m.add_class::<PyRealBounds>()?;
    m.add_class::<PyRealEulerAngles2d>()?;
    m.add_class::<PyRealEulerAngles3d>()?;
    m.add_class::<PyRealHsvColor>()?;
    m.add_class::<PyRealMatrix4x3>()?;
    m.add_class::<PyRealOrientation>()?;
    m.add_class::<PyRealPlane2d>()?;
    m.add_class::<PyRealPlane3d>()?;
    m.add_class::<PyRealPoint2d>()?;
    m.add_class::<PyRealPoint3d>()?;
    m.add_class::<PyRealQuaternion>()?;
    m.add_class::<PyRealRectangle2d>()?;
    m.add_class::<PyRealRectangle3d>()?;
    m.add_class::<PyRealRgbColor>()?;
    m.add_class::<PyRealVector2d>()?;
    m.add_class::<PyRealVector3d>()?;
    m.add_class::<PyRectangle2d>()?;
    m.add_class::<PyRgbColor>()?;
    m.add_class::<PyShortBounds>()?;
    m.add_class::<PyStringIdData>()?;
    m.add_class::<PyTagFieldType>()?;
    m.add_class::<PyTagFileHeader>()?;
    m.add_class::<PyTagReferenceData>()?;
    m.add_class::<PyTitle>()?;
    m.add_function(pyo3::wrap_pyfunction!(parse_group_tag, m)?)?;
    m.add_function(pyo3::wrap_pyfunction!(format_group_tag, m)?)?;
    m.add("AngleBounds", m.getattr("RealBounds")?)?;
    m.add("FractionBounds", m.getattr("RealBounds")?)?;
    Ok(())
}
