//! Keeps `parity_symbols/generated.rs` in step with the workspace
//! `parity.toml`.
//!
//! The generated file has one function per `[engine.*]` area, gated on the
//! area's features, naming each listed symbol; `tests/parity_symbols.rs`
//! compiles it, so a renamed or removed symbol breaks that build. This test
//! fails when the checked-in file no longer matches `parity.toml`, and does
//! not compile the file itself, so it can always rewrite it:
//!
//! ```sh
//! BLAM_PARITY_REGENERATE=1 cargo test -p blam-tags --test parity_manifest
//! ```

use std::path::PathBuf;

const FEATURES: &[&str] = &["audio", "iostore"];

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()
}

fn generated_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/parity_symbols/generated.rs")
}

/// The last path segment, ignoring any turbofish or `as fn(..)` coercion.
fn last_segment(symbol: &str) -> &str {
    let path = symbol.split(" as ").next().unwrap();
    let path = path.split("::<").next().unwrap();
    path.rsplit("::").next().unwrap()
}

/// The line that names `symbol`: a function or method is named as a value,
/// anything else (a type, trait, constant) is imported.
fn naming_line(symbol: &str) -> String {
    let lowercase = last_segment(symbol).chars().next().is_some_and(|c| c.is_ascii_lowercase());
    if lowercase { format!("    let _ = {symbol};") } else { format!("    use {symbol} as _;") }
}

fn render(parity: &str) -> Result<String, String> {
    let doc: toml::Table = parity.parse().map_err(|e| format!("parity.toml: {e}"))?;
    let engine = doc
        .get("engine")
        .and_then(|v| v.as_table())
        .ok_or("parity.toml has no [engine] table")?;

    let mut out = String::from(
        "// @generated by blam-tags/tests/parity_manifest.rs from parity.toml.\n\
         // Do not edit; regenerate with\n\
         // BLAM_PARITY_REGENERATE=1 cargo test -p blam-tags --test parity_manifest\n",
    );
    for (area, entry) in engine {
        let entry = entry.as_table().ok_or(format!("[engine.{area}] is not a table"))?;
        let symbols = entry
            .get("symbols")
            .and_then(|v| v.as_array())
            .filter(|a| !a.is_empty())
            .ok_or(format!("[engine.{area}] needs a non-empty `symbols` list"))?;
        let features: Vec<&str> = match entry.get("features") {
            None => Vec::new(),
            Some(v) => v
                .as_array()
                .ok_or(format!("[engine.{area}] features is not a list"))?
                .iter()
                .map(|f| f.as_str().ok_or(format!("[engine.{area}] feature is not a string")))
                .collect::<Result<_, _>>()?,
        };
        for f in &features {
            if !FEATURES.contains(f) {
                return Err(format!("[engine.{area}] names unknown feature `{f}`"));
            }
        }

        out.push('\n');
        if !features.is_empty() {
            let cfgs: Vec<String> = features.iter().map(|f| format!("feature = \"{f}\"")).collect();
            out.push_str(&format!("#[cfg(all({}))]\n", cfgs.join(", ")));
        }
        out.push_str(&format!("pub fn {}() {{\n", area.replace('-', "_")));
        for s in symbols {
            let s = s.as_str().ok_or(format!("[engine.{area}] symbol is not a string"))?;
            if !s.starts_with("blam_tags::") {
                return Err(format!("[engine.{area}] symbol `{s}` must start with `blam_tags::`"));
            }
            out.push_str(&naming_line(s));
            out.push('\n');
        }
        out.push_str("}\n");
    }
    Ok(out)
}

#[test]
fn generated_file_matches_parity_toml() {
    let parity = std::fs::read_to_string(workspace_root().join("parity.toml")).unwrap();
    let expected = render(&parity).unwrap();
    let path = generated_path();
    if std::env::var_os("BLAM_PARITY_REGENERATE").is_some() {
        std::fs::write(&path, &expected).unwrap();
        return;
    }
    let actual = std::fs::read_to_string(&path).unwrap_or_default();
    assert!(
        actual == expected,
        "{} does not match parity.toml; regenerate it with\n  \
         BLAM_PARITY_REGENERATE=1 cargo test -p blam-tags --test parity_manifest",
        path.display(),
    );
}

#[test]
fn naming_line_imports_types_and_names_functions() {
    assert_eq!(naming_line("blam_tags::TagFile"), "    use blam_tags::TagFile as _;");
    assert_eq!(naming_line("blam_tags::TagFile::root"), "    let _ = blam_tags::TagFile::root;");
    assert_eq!(naming_line("blam_tags::TagFile::read::<&str>"), "    let _ = blam_tags::TagFile::read::<&str>;");
    assert_eq!(
        naming_line("blam_tags::Fsb5::open as fn(&'static str) -> _"),
        "    let _ = blam_tags::Fsb5::open as fn(&'static str) -> _;",
    );
}

#[test]
fn render_refuses_bad_entries() {
    assert!(render("[engine.x]\nsymbols = []\n").is_err());
    assert!(render("[engine.x]\nsymbols = [\"std::fs::read\"]\n").is_err());
    assert!(render("[engine.x]\nsymbols = [\"blam_tags::TagFile\"]\nfeatures = [\"nope\"]\n").is_err());
}
