# Hand-written stubs for the facade types defined in `src/manual/`.
#
# These path-handle classes carry lifetimes that cannot be mechanically
# wrapped, so `blam-tags-bindgen` skips them (strategy = "manual" in
# bindings.toml) and appends this file verbatim to the generated
# `blam_tags.pyi`. Keep the signatures here in sync with
# `src/manual/handles.rs`.


class TagFile:
    """An open tag file — the root handle of the facade.

    Load one with [`TagFile.read`] (or [`TagFile.read_from_bytes`]), reach the
    top of the tag tree with [`TagFile.root`], edit through the returned
    [`TagStruct`] / [`TagField`] / [`TagBlock`] handles, then persist with
    [`TagFile.write`]. A tag may also carry separate dependency-list,
    import-info, and asset-depot-storage structs, reached with
    [`TagFile.dependency_list`] and friends. Every handle borrows this file, so
    a structural edit (adding/removing block elements) invalidates outstanding
    handles; re-fetch them after mutating a block."""
    @staticmethod
    def new(schema_path: str | os.PathLike[str]) -> TagFile: ...
    @staticmethod
    def read(path: str | os.PathLike[str]) -> TagFile: ...
    @staticmethod
    def read_from_bytes(bytes: bytes) -> TagFile: ...
    @staticmethod
    def read_dependency_references(path: str | os.PathLike[str]) -> list[tuple[int, str]] | None: ...
    def write(self, path: str | os.PathLike[str]) -> None: ...
    def write_atomic(self, path: str | os.PathLike[str]) -> None: ...
    def write_to_bytes(self) -> bytes: ...
    def recompute_checksum(self) -> None: ...
    def add_dependency_list(self, schema_path: str | os.PathLike[str]) -> None: ...
    def remove_dependency_list(self) -> None: ...
    def add_import_info(self, schema_path: str | os.PathLike[str]) -> None: ...
    def remove_import_info(self) -> None: ...
    def add_asset_depot_storage(self, schema_path: str | os.PathLike[str]) -> None: ...
    def remove_asset_depot_storage(self) -> None: ...
    def root(self) -> TagStruct: ...
    def dependency_list(self) -> TagStruct | None: ...
    def import_info(self) -> TagStruct | None: ...
    def asset_depot_storage(self) -> TagStruct | None: ...
    @property
    def group_tag(self) -> str: ...
    @property
    def group_version(self) -> int: ...
    @property
    def endian(self) -> Endian: ...
    @property
    def classic_engine(self) -> str | None: ...
    def __repr__(self) -> str: ...

class TagStruct:
    """A handle to one struct (a fixed field-set) inside an open [`TagFile`]."""
    @property
    def name(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def path(self) -> str: ...
    @property
    def raw(self) -> bytes: ...
    def field_names(self) -> list[str]: ...
    def fields(self) -> list[TagField]: ...
    def fields_all(self) -> list[TagField]: ...
    def field(self, name: str) -> TagField | None: ...
    def field_path(self, path: str) -> TagField | None: ...
    def descend(self, path: str) -> TagStruct | None: ...
    def __repr__(self) -> str: ...

class TagField:
    """A handle to one field inside a [`TagStruct`].

    Read [`TagField.value`] for scalar fields, or descend into structured
    fields with [`TagField.as_struct`] / [`TagField.as_block`] /
    [`TagField.as_array`] / [`TagField.as_resource`] / [`TagField.as_data`].
    Enum and flag fields expose their full catalog through [`TagField.options`];
    flag fields also have [`TagField.get_flag`] / [`TagField.set_flag`]."""
    @property
    def name(self) -> str: ...
    @property
    def clean_name(self) -> str: ...
    @property
    def display_name(self) -> str: ...
    @property
    def explanation(self) -> str | None: ...
    @property
    def ordinal(self) -> int: ...
    @property
    def type_name(self) -> str: ...
    @property
    def field_type(self) -> TagFieldType: ...
    @property
    def data_definition_name(self) -> str | None: ...
    @property
    def path(self) -> str: ...
    @property
    def value(self) -> object: ...
    def set(self, new_value: object) -> None: ...
    def flag_names(self) -> list[tuple[int, str]] | None: ...
    def options(self) -> TagOptions | None: ...
    def get_flag(self, name: str) -> bool: ...
    def set_flag(self, name: str, on: bool) -> None: ...
    def as_struct(self) -> TagStruct | None: ...
    def as_block(self) -> TagBlock | None: ...
    def as_array(self) -> TagArray | None: ...
    def as_resource(self) -> TagResource | None: ...
    def as_data(self) -> bytes | None: ...
    def is_function_data(self) -> bool: ...
    def as_function(self) -> TagFunction | None: ...
    def __repr__(self) -> str: ...

class TagBlock:
    """A handle to a tag block (a resizable array of [`TagStruct`] elements).

    Indexable and sized like a Python sequence (`len(block)`, `block[i]`).
    Mutating methods ([`TagBlock.add`], [`TagBlock.insert`], … ) change the
    element count and invalidate other outstanding handles into the same file.
    Copy elements between blocks with [`TagBlock.snapshot`] and
    [`TagBlock.paste`]."""
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __getitem__(self, index: int) -> TagStruct: ...
    @property
    def element_size(self) -> int: ...
    @property
    def path(self) -> str: ...
    @property
    def classic_block_header(self) -> bytes | None: ...
    def snapshot(self, index: int) -> TagBlockElement: ...
    def add(self) -> int: ...
    def insert(self, index: int) -> None: ...
    def duplicate(self, index: int) -> int: ...
    def delete(self, index: int) -> None: ...
    def swap(self, i: int, j: int) -> None: ...
    def move_element(self, from_: int, to: int) -> None: ...
    def paste(self, index: int, element: TagBlockElement) -> int: ...
    def clear(self) -> None: ...
    def __repr__(self) -> str: ...

class TagArray:
    """A handle to a fixed-count array of [`TagStruct`] elements.

    Indexable and sized like a sequence, but the count is fixed: elements can
    be swapped or replaced ([`TagArray.swap`], [`TagArray.replace`]) but not
    added or removed."""
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __getitem__(self, index: int) -> TagStruct: ...
    @property
    def path(self) -> str: ...
    def snapshot(self, index: int) -> TagBlockElement: ...
    def swap(self, i: int, j: int) -> None: ...
    def replace(self, index: int, element: TagBlockElement) -> None: ...
    def __repr__(self) -> str: ...

class TagResource:
    """A handle to a pageable resource attached to a field."""
    @property
    def kind(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def inline_bytes(self) -> bytes: ...
    @property
    def exploded_payload(self) -> bytes | None: ...
    @property
    def xsync_payload(self) -> bytes | None: ...
    def as_struct(self) -> TagStruct | None: ...
    def __repr__(self) -> str: ...

class TagOptions:
    """The full option catalog of an enum or flags field.

    For an enum, [`names`] is every variant in declaration order (the list
    index is the stored value) and [`current`] is the stored index. For flags,
    [`flags`] lists `(bit, name, is_set)` for every defined bit."""
    @property
    def is_enum(self) -> bool: ...
    @property
    def is_flags(self) -> bool: ...
    @property
    def names(self) -> list[str]: ...
    @property
    def current(self) -> int | None: ...
    @property
    def current_name(self) -> str | None: ...
    @property
    def flags(self) -> list[tuple[int, str, bool]]: ...
    def __repr__(self) -> str: ...

class TagFunction:
    """A parsed tag function (`mapping_function`)."""
    @property
    def function_type(self) -> str: ...
    def is_constant(self) -> bool: ...
    def as_constant(self) -> float | None: ...
    def is_clamped(self) -> bool: ...
    def evaluate(self, input: float, range: float) -> float: ...
    def evaluate_legacy(self, input: float, range: float) -> float: ...
    def __repr__(self) -> str: ...

class TagBlockElement:
    """An opaque snapshot of a block or array element, for copy/paste."""
    def __repr__(self) -> str: ...
