//! Gate: can every cooked package's *header* be regenerated byte-exactly?
//!
//! `ce_export_roundtrip` proves each export's serial range. A package is that
//! plus a header — summary, name map, bulk data map, import and export maps,
//! export bundles, dependency bundles and arcs — and rebuilding a package means
//! producing all of it, not just the payloads.
//!
//! This is a much stronger gate than the export one, and deliberately the next
//! step: it catches name-map ordering, alignment and summary-offset bugs that
//! per-export work cannot see, because those only manifest when the header is
//! written as a whole. `FZenPackageHeader::serialize` recomputes its own
//! internal offsets by seeking back, so this measures whether that recomputation
//! agrees with what the cooker actually wrote.
//!
//! The export payloads are appended verbatim here — this is a header gate.
//! Recomputing export offsets is the *next* step, and it is only meaningful once
//! an unmodified package rebuilds exactly.
//!
//! Run: `ce_package_roundtrip`
use std::collections::BTreeMap;
use std::io::{Cursor, Write};

use blam_tags::iostore::container_header::{EIoContainerHeaderVersion, StoreEntry};
use blam_tags::iostore::ue_types::EIoStoreTocVersion;
use blam_tags::iostore::zen::FZenPackageHeader;
use blam_tags::iostore::IoStoreArchive;

const PAKS: &str = "/Users/camden/Halo/halo-campaign-evolved_pc/Meteorite/Content/Paks";
const CV: EIoStoreTocVersion = EIoStoreTocVersion::ReplaceIoChunkHashWithIoHash;
const HV: EIoContainerHeaderVersion = EIoContainerHeaderVersion::SoftPackageReferences;

fn main() {
    let mut utocs: Vec<_> = std::fs::read_dir(PAKS)
        .expect("read Paks")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x.eq_ignore_ascii_case("utoc")))
        .filter(|p| !p.file_name().is_some_and(|n| n.eq_ignore_ascii_case("global.utoc")))
        .collect();
    utocs.sort();
    let archives: Vec<IoStoreArchive> =
        utocs.iter().filter_map(|u| IoStoreArchive::open(u).ok()).collect();

    let (mut total, mut same, mut unreadable, mut unwritable) = (0usize, 0usize, 0usize, 0usize);
    let mut samples: Vec<String> = Vec::new();
    let mut size_mismatch = 0usize;
    let mut first_diff_hist: BTreeMap<&'static str, usize> = BTreeMap::new();

    for a in &archives {
        for e in a.entries() {
            let lo = e.path.to_ascii_lowercase();
            if !lo.ends_with(".uasset") && !lo.ends_with(".umap") {
                continue;
            }
            let Ok(b) = a.read(&e.path) else { continue };
            let Ok(h) = FZenPackageHeader::deserialize(&mut Cursor::new(&b), None, CV, HV, None)
            else {
                unreadable += 1;
                continue;
            };
            total += 1;

            let mut out = Cursor::new(Vec::with_capacity(b.len()));
            let mut store_entry = StoreEntry::default();
            if let Err(err) = h.serialize(&mut out, &mut store_entry, HV) {
                unwritable += 1;
                if samples.len() < 8 {
                    samples.push(format!("{}: {err:#}", h.package_name()));
                }
                continue;
            }
            let mut out = out.into_inner();
            let header_len = h.summary.header_size as usize;
            // Append the export payloads untouched — this gate is about the
            // header. If the regenerated header is a different length the two
            // can never line up, so report that separately.
            if header_len <= b.len() {
                out.write_all(&b[header_len..]).expect("append payloads");
            }

            if out == b {
                same += 1;
                continue;
            }
            if out.len() != b.len() {
                size_mismatch += 1;
            }
            let at = out.iter().zip(&b).position(|(x, y)| x != y).unwrap_or(out.len().min(b.len()));
            // Which part of the header did it first go wrong in?
            let zone = h
                .summary
                .section_at(at)
                .unwrap_or("payload (header length differs)");
            *first_diff_hist.entry(zone).or_default() += 1;
            if samples.len() < 8 {
                let lo = at.saturating_sub(8);
                samples.push(format!(
                    "{} :: {} bytes in, {} out, header {}\n    first difference at {at} ({zone})\n    \
                     orig {:02x?}\n    ours {:02x?}",
                    h.package_name(),
                    b.len(),
                    out.len(),
                    header_len,
                    &b[lo..(at + 8).min(b.len())],
                    &out[lo..(at + 8).min(out.len())],
                ));
            }
        }
    }

    println!("packages examined    {total}");
    println!("rebuilt exactly      {same} ({:.4}%)", 100.0 * same as f64 / total.max(1) as f64);
    println!("differ               {}", total - same - unwritable);
    println!("  of which resized   {size_mismatch}");
    println!("refused to write     {unwritable}");
    println!("unreadable (skipped) {unreadable}");

    if !first_diff_hist.is_empty() {
        println!("\nfirst difference by header zone:");
        let mut v: Vec<_> = first_diff_hist.iter().collect();
        v.sort_by_key(|(_, n)| std::cmp::Reverse(**n));
        for (z, n) in v {
            println!("  {n:>7}  {z}");
        }
    }
    for s in &samples {
        println!("\n{s}");
    }
    if same != total {
        std::process::exit(1);
    }
}
