// @generated by blam-tags/tests/parity_manifest.rs from parity.toml.
// Do not edit; regenerate with
// BLAM_PARITY_REGENERATE=1 cargo test -p blam-tags --test parity_manifest

pub fn animation_export() {
    let _ = blam_tags::extract::animation::write_group_jma;
    let _ = blam_tags::extract::animation::write_ce_group_jma;
    let _ = blam_tags::extract::animation::animations_to_dir;
    use blam_tags::animation::jma::JmaKind as _;
}

pub fn animation_graphs() {
    let _ = blam_tags::AnimationGraph::from_tag;
    let _ = blam_tags::Animation::new;
    let _ = blam_tags::animation::classic::CeAnimations::new;
}

pub fn arrays() {
    let _ = blam_tags::TagArray::element;
    let _ = blam_tags::TagArrayMut::swap;
    let _ = blam_tags::TagArrayMut::replace_element;
}

pub fn bitmaps() {
    let _ = blam_tags::Bitmap::new;
    let _ = blam_tags::Bitmap::image;
    use blam_tags::BitmapImage as _;
    use blam_tags::BitmapFormat as _;
    let _ = blam_tags::bitmap::color_plate;
    use blam_tags::bitmap::ColorPlate as _;
}

pub fn blocks() {
    let _ = blam_tags::TagBlockMut::add_element;
    let _ = blam_tags::TagBlockMut::insert_element;
    let _ = blam_tags::TagBlockMut::duplicate_element;
    let _ = blam_tags::TagBlockMut::delete_element;
    let _ = blam_tags::TagBlockMut::swap_elements;
    let _ = blam_tags::TagBlockMut::move_element;
    let _ = blam_tags::TagBlockMut::clear;
    let _ = blam_tags::TagBlockMut::paste_element;
    let _ = blam_tags::TagBlock::element_snapshot;
}

pub fn bsp_to_ass() {
    let _ = blam_tags::AssFile::from_scenario_structure_bsp;
    let _ = blam_tags::AssFile::from_render_model;
    let _ = blam_tags::extract::geometry::scenario_geometry;
    let _ = blam_tags::extract::geometry::emit_ce_bsp_jms;
}

pub fn classic_read() {
    let _ = blam_tags::classic::read_classic_tag_file;
    use blam_tags::classic::ClassicEngine as _;
    use blam_tags::classic::ClassicHeader as _;
    let _ = blam_tags::classic::classic_roundtrip;
    let _ = blam_tags::TagFile::classic_engine;
}

pub fn collision_import() {
    let _ = blam_tags::collision_import::collision_model_from_jms;
    let _ = blam_tags::collision_import::collision_bsp_from_triangles;
}

pub fn collision_verify() {
    let _ = blam_tags::collision_verify::test_collision_model;
    let _ = blam_tags::collision_verify::test_collision_bsp;
}

pub fn conversion() {
    let _ = blam_tags::convert::analyze_conversion;
    let _ = blam_tags::convert::analyze_conversion_routed;
    let _ = blam_tags::convert::conversion_routes;
    let _ = blam_tags::convert::conversion_targets_for;
    let _ = blam_tags::convert::read_tag_for_conversion;
    use blam_tags::convert::TagConversionReport as _;
    use blam_tags::convert::LossPolicy as _;
    let _ = blam_tags::convert::prepare_companion_outputs;
    use blam_tags::convert::CompanionTagDraft as _;
}

pub fn definitions() {
    let _ = blam_tags::TagFile::definitions;
    use blam_tags::TagStructDefinition as _;
    use blam_tags::TagFieldDefinition as _;
    use blam_tags::TagBlockDefinition as _;
}

pub fn dependency_rebuild() {
    let _ = blam_tags::TagFile::rebuild_dependency_list::<&str>;
}

pub fn dependency_streams() {
    let _ = blam_tags::TagFile::add_dependency_list::<&str>;
    let _ = blam_tags::TagFile::remove_dependency_list;
    let _ = blam_tags::TagFile::add_import_info::<&str>;
    let _ = blam_tags::TagFile::remove_import_info;
    let _ = blam_tags::TagFile::add_asset_depot_storage::<&str>;
    let _ = blam_tags::TagFile::remove_asset_depot_storage;
    let _ = blam_tags::TagFile::dependency_list;
    let _ = blam_tags::TagFile::import_info;
    let _ = blam_tags::TagFile::read_dependency_references::<&str>;
}

pub fn field_paths() {
    use blam_tags::TagFieldPath as _;
    use blam_tags::TagFieldPathSegment as _;
    let _ = blam_tags::TagFieldPath::push_name as fn(&mut _, &'static str);
    let _ = blam_tags::clean_field_name;
    let _ = blam_tags::parse_field_name;
}

pub fn field_read() {
    let _ = blam_tags::TagFile::root;
    let _ = blam_tags::TagStruct::fields;
    let _ = blam_tags::TagStruct::field;
    let _ = blam_tags::TagStruct::field_path;
    let _ = blam_tags::TagStruct::descend;
    let _ = blam_tags::TagField::value;
    let _ = blam_tags::TagField::type_name;
    use blam_tags::TagFieldData as _;
}

pub fn field_write() {
    let _ = blam_tags::TagFile::root_mut;
    let _ = blam_tags::TagStructMut::field_path_mut;
    let _ = blam_tags::TagFieldMut::set;
    use blam_tags::TagSetError as _;
}

pub fn flags_and_enums() {
    let _ = blam_tags::TagField::flag;
    let _ = blam_tags::TagField::options;
    let _ = blam_tags::TagFieldMut::flag_mut;
    let _ = blam_tags::TagFlagMut::toggle;
    use blam_tags::TagOptions as _;
}

pub fn function_editor() {
    let _ = blam_tags::tag_function::editor::TagFunctionEditor::parse;
    let _ = blam_tags::tag_function::editor::TagFunctionEditor::set_function_type;
    let _ = blam_tags::tag_function::editor::TagFunctionEditor::set_clamp_range;
    let _ = blam_tags::tag_function::editor::TagFunctionEditor::to_bytes;
}

pub fn games() {
    let _ = blam_tags::game::Game::of;
    use blam_tags::game::Title as _;
}

pub fn group_tags() {
    let _ = blam_tags::parse_group_tag;
    let _ = blam_tags::format_group_tag;
}

#[cfg(all(feature = "iostore"))]
pub fn iostore_containers() {
    let _ = blam_tags::iostore::IoStoreArchive::open as fn(&'static str) -> _;
    let _ = blam_tags::iostore::IoStoreArchive::entries;
    let _ = blam_tags::iostore::IoStoreArchive::read;
    let _ = blam_tags::iostore::is_tag_payload;
    let _ = blam_tags::iostore::parse_ublock_stem;
}

#[cfg(all(feature = "iostore"))]
pub fn iostore_world() {
    let _ = blam_tags::iostore::world::World::open as fn(&'static str, _) -> _;
    let _ = blam_tags::iostore::world::World::packages;
    let _ = blam_tags::iostore::world::World::read_package;
    let _ = blam_tags::iostore::world::compare_mount_paths;
    let _ = blam_tags::iostore::world::package_name_from_entry;
}

pub fn jms_sources() {
    let _ = blam_tags::JmsFile::parse;
    let _ = blam_tags::jms_split::split_oversized_sections;
    let _ = blam_tags::gltf::jms_from_gltf_path;
}

pub fn layout_compare() {
    let _ = blam_tags::schema_compare::compare_root_layout;
    use blam_tags::schema_compare::LayoutComparison as _;
}

pub fn math() {
    use blam_tags::math::RealQuaternion as _;
    use blam_tags::math::RealPoint3d as _;
    use blam_tags::math::RealMatrix4x3 as _;
}

pub fn model_to_jms() {
    let _ = blam_tags::JmsFile::from_render_model;
    let _ = blam_tags::JmsFile::from_gbxmodel;
    let _ = blam_tags::JmsFile::from_collision_model;
    let _ = blam_tags::JmsFile::from_physics_model_with_skeleton;
    let _ = blam_tags::JmsFile::write::<Vec<u8>>;
}

pub fn monolithic_cache() {
    let _ = blam_tags::monolithic::MonolithicCache::open as fn(&'static str) -> _;
    let _ = blam_tags::monolithic::MonolithicCache::iter_tags;
    let _ = blam_tags::monolithic::MonolithicCache::read_tag;
    let _ = blam_tags::monolithic::MonolithicCache::read_tag_by_name;
}

pub fn particle_models() {
    let _ = blam_tags::particle_model::read_particle_model;
    let _ = blam_tags::extract::particle_model::particle_model_geometry;
    use blam_tags::JmiFile as _;
}

pub fn physics_import() {
    let _ = blam_tags::physics_import::physics_model_from_jms;
    let _ = blam_tags::hull::convex_hull;
}

pub fn render_geometry() {
    let _ = blam_tags::render_geometry::RenderGeometryResource::parse;
    let _ = blam_tags::render_geometry::decode_vertex_buffer;
    let _ = blam_tags::render_geometry::hydrate;
}

pub fn render_import() {
    let _ = blam_tags::render_import::render_model_from_jms;
    use blam_tags::render_import::RenderOptions as _;
    let _ = blam_tags::prt::sh_transfer;
}

pub fn render_method_bake() {
    let _ = blam_tags::render_method::RenderMethod::bake as fn(&mut _, &_, &_, fn(&str) -> Option<_>, f32) -> _;
    let _ = blam_tags::render_method::resolve_pixel_user_cbuffer;
    let _ = blam_tags::render_method::rebuild_cbuffer_bytes_at_time;
    use blam_tags::render_method::BakeError as _;
}

pub fn render_method_resolve() {
    let _ = blam_tags::render_method::ResolvedRenderMethod::resolve as fn(&_, &_, fn(&str) -> Option<_>) -> _;
    let _ = blam_tags::render_method::RenderMethodChoices::resolve;
    use blam_tags::render_method::ResolvedParameter as _;
}

pub fn resource_copy() {
    let _ = blam_tags::TagFieldMut::copy_resource_from;
    let _ = blam_tags::TagFieldMut::init_resource;
    let _ = blam_tags::TagFieldMut::clear_resource;
}

pub fn resources() {
    let _ = blam_tags::TagResource::kind;
    let _ = blam_tags::TagResource::inline_bytes;
    let _ = blam_tags::TagResource::exploded_payload;
    let _ = blam_tags::TagResource::xsync_payload;
}

pub fn schema_compat() {
    let _ = blam_tags::schema_compat::compare_group_layouts;
    let _ = blam_tags::schema_compat::struct_trees_are_wire_identical;
    use blam_tags::schema_compat::GroupComparison as _;
}

#[cfg(all(feature = "audio"))]
pub fn sound_banks() {
    let _ = blam_tags::audio::SoundBanks::open_pc;
    let _ = blam_tags::audio::SoundBanks::resolve;
    let _ = blam_tags::audio::fsb5::Fsb5::open as fn(&'static str) -> _;
    let _ = blam_tags::audio::fsb5::fmod_bank_subsound_id_hash;
    let _ = blam_tags::audio::bank_path_from_tags_root;
    let _ = blam_tags::audio::WwiseBanks::open_pc;
    let _ = blam_tags::audio::WwiseBanks::open_pc_language;
}

#[cfg(all(feature = "audio"))]
pub fn sound_decode() {
    let _ = blam_tags::audio::vorbis::decode_subsound;
    let _ = blam_tags::audio::vorbis::decode_ogg_vorbis;
    let _ = blam_tags::audio::classic::decode_opus;
    let _ = blam_tags::audio::classic::decode_xbox_adpcm;
    let _ = blam_tags::audio::classic::decode_pcm;
}

#[cfg(all(feature = "audio"))]
pub fn sound_encode() {
    let _ = blam_tags::audio::vorbis::encode_ogg_vorbis;
    let _ = blam_tags::audio::classic::encode_opus;
    let _ = blam_tags::audio::classic::encode_xbox_adpcm;
    let _ = blam_tags::audio::classic::encode_pcm;
}

pub fn structure_import() {
    let _ = blam_tags::sbsp_import::structure_bsp_from_ass_with;
    let _ = blam_tags::ass_parse::parse;
}

pub fn tag_file_io() {
    let _ = blam_tags::TagFile::read::<&str>;
    let _ = blam_tags::TagFile::read_from_bytes;
    let _ = blam_tags::TagFile::write::<&str>;
    let _ = blam_tags::TagFile::write_atomic::<&str>;
    let _ = blam_tags::TagFile::write_to_bytes;
    let _ = blam_tags::TagFile::recompute_checksum;
}

pub fn tag_file_new() {
    let _ = blam_tags::TagFile::new::<&str>;
    let _ = blam_tags::TagLayout::from_json as fn(&'static str) -> _;
    use blam_tags::TagGroupMeta as _;
    use blam_tags::TagSchemaError as _;
}

pub fn tag_functions() {
    let _ = blam_tags::tag_function::TagFunction::parse;
    let _ = blam_tags::tag_function::TagFunction::evaluate;
    let _ = blam_tags::tag_function::TagFunction::as_constant;
    use blam_tags::tag_function::H2Function as _;
}

pub fn tag_header() {
    let _ = blam_tags::TagFileHeader::peek::<&str>;
    let _ = blam_tags::TagFile::group;
}

pub fn tag_paths() {
    let _ = blam_tags::paths::derive_tags_root;
    let _ = blam_tags::paths::tag_stem;
    let _ = blam_tags::paths::resolve_tag_path;
    let _ = blam_tags::paths::group_tag_to_extension;
}

#[cfg(all(feature = "iostore"))]
pub fn unreal_meshes() {
    let _ = blam_tags::JmsFile::from_ue_skeletal_mesh;
    let _ = blam_tags::JmsFile::from_ue_meshes;
}
